### ISSUE TITLE
Album size overflowing in AlbumDetail.js

### ISSUE THREAD

**Issue by Salman-Inayat** [navidrome/navidrome#1009]
Album size goes to the next line when viewed on extra small screen. 

![image](https://user-images.githubusercontent.com/45660519/114272551-0fda3b00-9a30-11eb-92f6-e24838bfbacf.png)

It would be better if we display number of songs, duration and size in multiple lines

![image](https://user-images.githubusercontent.com/45660519/114272599-40ba7000-9a30-11eb-9aba-976355743020.png)

**Comment by deluan** [comment]
Thanks for tackling this. But instead of putting each info in its own line (using a lot of the vertical space of the details area, it would be better just to make sure each field does not "break" in two lines. I'm not sure how to do this in CSS, but in the example above, only the size would go to the next line, like this:
```
10 Songs . 33:40
49.1 MB
```

**Comment by Salman-Inayat** [comment]
Album size is only  shifted to next line when viewed on small screen. 

![image](https://user-images.githubusercontent.com/45660519/115006351-341b9900-9ec2-11eb-8fe4-e3c40f21fe97.png)

**Comment by deluan** [comment]
Ah, ok, that's not what was pictured in the previous screenshot. Will take a look at the PR, thanks!

**Comment by Salman-Inayat** [comment]
I modified it after you mentioned only album size should go to next line.

**Comment by deluan** [comment]
Fixed by #1071
