### ISSUE TITLE
[UI Bug] Spotify-ish Theme "Add to Playlist" covers CANCEL/ADD Buttons with the Drop Dropdown Element.

### ISSUE THREAD

**Issue by TheFlatworm** [navidrome/navidrome#1064]
Spotify-ish "Add to Playlist" covers CANCEL/ADD buttons with the drop dropdown element.

<img width="597" alt="Screen Shot 2021-04-27 at 12 27 32 PM" src="https://user-images.githubusercontent.com/5423879/116301636-21705200-a755-11eb-8bc7-e0999a036cab.png">

Firefox browser
Navidrome Version: | 0.42.0 (f1bd736b)

**Comment by Dnouv** [comment]
@TheFlatworm, thanks for reporting the issue; I think the dropdown options menu disappears whenever one selects an option, so that might not conflict with ADD button, it is the default behavior.
If you have got any suggestions, please feel free to provide them.

After selecting the option:
![image](https://user-images.githubusercontent.com/61188295/116312691-671b3200-a7ca-11eb-946e-4364150b937d.png)

**Comment by deluan** [comment]
This was already the behaviour with previous versions and other themes:

<img width="718" alt="Screen Shot 2021-04-27 at 5 06 13 PM" src="https://user-images.githubusercontent.com/331353/116312819-f6005e00-a77a-11eb-9ec6-21d93da532d8.png">

The difference is that it is showing a part of the button...

**Comment by deluan** [comment]
Hey @TheFlatworm , I'm closing this as it is the expected behaviour. Feel free to reply with you have any concerns.
