### ISSUE TITLE
How to bypass default auth login page ?

### ISSUE THREAD

**Issue by shgurbanov** [navidrome/navidrome#1221]
I would like that when opening the main page of the engine, not the authorization page comes out, but the main page of the player with albums.

Now
![Screenshot 2021-07-01 163816](https://user-images.githubusercontent.com/5786682/124125802-0e4a6d00-da8b-11eb-9937-dc3e6b28b335.jpg)

How to get that without authentication(as default main page when open site)
![Screenshot 2021-07-01 163910](https://user-images.githubusercontent.com/5786682/124125726-0094e780-da8b-11eb-91dc-6304aaab747f.jpg)

And then user passed registration(by the way ! registration not available) and login with his own credentials (for playlist owning as example).

**Comment by Mikhail5555** [comment]
It is currently not supported to bypass login (consider having a Guest user with maybe an easy password) and have the ability to login at the same time. Maybe you could achieve something like this with a special SSO, which falls back to some default user if no-one is logged it.
I would also heavily advice against just exposing your instance to the internet without any authentication.

**Comment by deluan** [comment]
Navidrome is meant to be a "personal" server, and not a public service. In this context, self-registration does not make much sense. We are working on a way to enable you to create links to selected music/albums/playlists that will allow you to share part of your library anonymously. See #748 

As for bypassing the login page, I second @Mikhail5555 opinion that you should not do this. For security reasons and also because this may cause you issues with copyright holders.

**Comment by certuna** [comment]
Even a public service like Spotify shows a login screen before the music.

**Comment by ToadCast** [comment]
> 
> 
> Even a public service like Spotify shows a login screen before the music.

This is partially true, you don't need to login to explore the albums and artists.

**Comment by deluan** [comment]
> > Even a public service like Spotify shows a login screen before the music.
> 
> This is partially true, you don't need to login to explore the albums and artists.

But Spotify has a team dedicated to secure their web app, and they don't have issues with copyright. Also their web app does not have a "download" button ;)

**Comment by ToadCast** [comment]
> 
> But Spotify has a team dedicated to secure their web app, and they don't have issues with copyright. Also their web app does not have a "download" button ;)

Oh they have some issue with the copyrights, but not the same kind we could have with Navidrome indeed 🙂. But it would only be to the owner of the server then. I guess the purpose of the issue was more about listening the music without account than downloading it.

Anyway, I meant that it's an understandable issue and desire. However, that doesn't seem to fit in the purpose of this software:

> What exactly is Navidrome?
> 
> It is a piece of software that **allows you** to listen to your own digital music in the same way you would with services like Spotify, Apple Music and others. It also allows you to easily **share your music and playlists with your friends and family**

**Comment by Mikhail5555** [comment]
I mean, with the new SSO feature, you could make this work.
Have a secret separate subdomain with a hard-coded Remote-User: Guest (WHICH YOU MOST DEFINITELY SHOULD HAVE AT LEAST AN IP WHITELIST ON)
And then a separate default subdomain which redirects to your SSO provider with the normal Auth flow & people having separate accounts.
But then again, I would still heavily advice against this approach or any approach which leaves any self-hosted service exposed to the internet with questionable (untested) security (No offence @deluan, i'm comparing it with password KeyCloak/Authelia which had security audits) which could possibly compromise your server and lead to legal/copyright issues.

**Comment by deluan** [comment]
Closing this as there are no plans for unauthenticated access, and you can achieve something similar with SSO as described above by @Mikhail5555
