### ISSUE TITLE
Favorites are sorted by addition order

### ISSUE THREAD

**Issue by jicho** [navidrome/navidrome#1289]
### Description
When you make albums favorite by pressing the stars they are visible in the same order as the hearts pressed.
Why isn't this ordered by Album name?

### Expected Behaviour
I would expect to have the order of the albums, not by the order of pressing hearts and/or the stars pressed.

### Steps to reproduce

1. Login
2. Click hearts random
3. Press favorites
4. You see the order or the albums as clicked on the hearts and not by name

### Platform information

 - Navidrome version: 0.44.1
 - Browser and version: Safari 14.1.2
 - Operating System: macOS

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by deluan** [comment]
@jicho Thanks for trying Navidrome! This is the expected behaviour: The Album List views were created to mimic the behaviour of Airsonic/Subsonic. We plan to make all views (including song/artist/genre/playlists) more flexible, allowing table/grid view and also allowing to specify the sort order, but for now this is not something we will "fix" in the current Favourites view.

@g4rry420 Sorry, but as I said above this is not something we want to change ATM

Another GH issue that cover this is: https://github.com/navidrome/navidrome/issues/1035. I'm closing this in favour of that one. Please follow it to receive updates

**Comment by jicho** [comment]
@deluan That sounds logical, I will survive till #1035 is implemented.
