### ISSUE TITLE
MP3 Tags being ignored

### ISSUE THREAD

**Issue by ch1nch4ch4** [navidrome/navidrome#1323]
### Description

I have imported MP3 files into NaviDrome all of which have Artist/Album/Title etc tagged however NaviDrome isn't able to see this and details Unknown artist / album etc. I have also imported a file from another user that works on their installation however on mine it doesn't.

### Expected Behaviour

Correct artist/album/tag data to be displayed.

### Steps to reproduce

1. Download mp3 https://1fichier.com/?u8r4kum52r5ew4sj3vge
2. Import into Library
3. View Song in library

### Platform information

Docker container - 
IMAGE :::: deluan/navidrome:latest@sha256:9fba9564f1fa35cb24e3f67f5a41cae90507c5b32d424aee86806bd9bc107cc9

Version: | 0.45.1 (c55e6590)

Browser: Safari 14.1.2
OS: macOS Big Sur: Version 11.5.2

<img width="1316" alt="Screenshot 2021-09-01 at 16 37 47" src="https://user-images.githubusercontent.com/12185719/131701178-ae7b262f-8d4e-42fd-9890-75e93b3c0a70.png">

<img width="1264" alt="Screenshot 2021-09-01 at 16 35 42" src="https://user-images.githubusercontent.com/12185719/131700947-378a0c70-2736-47b2-ab98-fe1e87d689ef.png">

**Comment by certuna** [comment]
I can not reproduce this on macOS, file gets scanned correctly with all metadata.

Does changing the scanner (ffmpeg instead of taglib) make a difference? So you are running Navidrome in Docker on macOS with the media as a remote Google Drive mount? That's a pretty complex scenario. If you run the native Navidrome macOS binary and/or with local files, does it still happen?

**Comment by ch1nch4ch4** [comment]
Hi and thanks for the advice. I updated the config and changed the scanner and it is now working. :-D
