### ISSUE TITLE
Add semantic class tags for currently playing song

### ISSUE THREAD

**Issue by KucharczykL** [navidrome/navidrome#1364]
### Is your feature request related to a problem? Please describe.

I use the WebScrobbler extension (https://github.com/web-scrobbler/web-scrobbler) to scrobble songs I'm listening to in my browser to services other than Last.fm and it worked with Navidrome until recently.

I believe currently it's broken because the `.songInfo` class was removed in https://github.com/navidrome/navidrome/commit/aa72d3d41ba84a1e39c69ce4a2622230c087832f
Looking at their repository, I think WebScrobbler was relying on it: https://github.com/web-scrobbler/web-scrobbler/commit/5e62c921b4545be36b7024213cd6b121a6005b31

### Describe the solution you'd like

It would be nice if the album and artist of the currently playing song were identified as such, for example using classes.
The reason why I ask this is that at the moment the information about artist, album, and year are a single string of text separated by dashes. This is possible to parse of course but if the order or position is ever changed, there would need to be another fix.
The parsing would also fail if any of them contained the `-` character.
Currently we have this:
```
<span class="jss407">Emika - Dva - 2013</span>
```
And I am asking it to be changed to something like this:
```
<span class="jss407">
 <span class="songArtist">Emika</span> - <span class="songAlbum">Dva</span> - 2013
</span>
```
(The year is not really important for this purpose but I suppose it might make sense to do the same with it.)

### Describe alternative solutions that would also satisfy this problem

Change nothing in Navidrom and just fix the Navidrome connector in the Web Scrobbler extension.
This would be quite fragile as any changes to the layout or order would probably break it again.

### Additional context

![image](https://user-images.githubusercontent.com/31072879/134662309-268fc198-be68-49fe-aac3-f6e76d9a210c.png)

**Comment by deluan** [comment]
Yeah, this kind of issues may happens from time to time with solutions that don't use well supported APIs. I actually fixed WebScrobbler in the past due to a similar issue, but as we restructured the `AudioTitle` component, this came up again. It is hard to keep track of third-party integrations, and make sure it all works...

I may take a look at this later, but a better approach is just use Navidrome's own scrobble features, specially because it is buffered and retriable, meaning that if Last.fm goes down or connectivity is broken, ND keeps retrying until it can submit the scrobbles, even if you close the browser or restart the server.

**Comment by KucharczykL** [comment]
I do appreciate Navidrome having its own Last.fm integration but I also use other services (LibreFM, ListenBrainz) and I use other services, including YouTube Music, Spotify, and Deezer. Having them all scrobble to the same services from one spot is a godsend!

That said, what would be a better solution to fix this long-term other than scraping and having the information in semantic tags like I described above? I assume the API requires authorization, right?

**Comment by deluan** [comment]
Ah yes, if you use other services, Navidrome does not support them (yet).

> That said, what would be a better solution to fix this long-term other than scraping and having the information in semantic tags like I described above? I assume the API requires authorization, right?

Yeah, I was not saying there is a better solution for something like a multisource scraper, just that scraping (and other form of non-documented integration) are always susceptible to such breaks.

Unfortunately I don't have time to dig into this issue and fix it myself, but would be glad to accept a PR that address this.

**Comment by KucharczykL** [comment]
See #1392

**Comment by deluan** [comment]
Hey @KucharczykL, thanks for the PR. I checked it, but it broke some styles. And because the previous code also had some small issues, I decided to fix it myself. I didn't included the `songYear` as it is not really required for this use case and it would complicate things a bit, making the `AudioTitle` component even harder to read. Hope this is fine for you.

**Comment by KucharczykL** [comment]
No problem at all, I'm just sorry I couldn't be of more help. I will take a look at how you fixed the issue and compare it to my naive solution to see how it's supposed to be done.

Thank you for fixing this!
