### ISSUE TITLE
[Web UI] Clicking on song, when having selected multiple files, plays only one song

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#1436]
0.46.0 Web UI:

1. Go to Songs view
2. Select All, or select multiple songs
3. Click on a song title

Observed behaviour: the player now only plays the one song clicked
Expected behaviour: the player creates a play queue of all selected songs, and plays the clicked song

**Comment by helper-uttam** [comment]
> @certuna What to do if the user select some songs and click on one that is not selected?

According to me, If user has selected some songs and they tries to click on one that is not selected then that particular not selected song should get selected. But the application plays that song instead of selecting it. It only selects the song when we click inside the checkbox.

Expected behavior should be if one song is selected and then if user tries to click on other song then it should also get selected. 
What's your opinion @deluan @certuna ?

**Comment by deluan** [comment]
The issue is selecting rows on click would be inconsistent to the current way to do it (using the checkboxes). Not sure if this is desirable...
