### ISSUE TITLE
Albums are splitted on artists

### ISSUE THREAD

**Issue by FabianPiconeDev** [navidrome/navidrome#1495]
Navidrome version: 0.47.0

I would expect that when showing albums, one album should only be shown one time, no matter if the songs in the album are from different artists.

What currently happens, is that albums are splitted on each artist.

![splitted albums](https://user-images.githubusercontent.com/4472725/143868197-bd5fda6f-9ab4-4984-801f-978cf9aca4c9.JPG)

**Comment by metalheim** [comment]
That is expected behavior, not a bug .  The reason is that there are a lot of albums with the same name from different artists. (These you wouldn't want clumped together into one) 

To avoid that, you need to either:

Set the "Album artist" Tag for all songs to be the same 
Or
Set the "compilation" tag to 1 for all songs

Any good tag editor (f.e. Mp3tag, Yate, kid3) can do that

**Comment by deluan** [comment]
Thanks for using Navidrome. @metalheim's answer is correct. See: https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

Also, there's a recent thread in Reddit about it: https://www.reddit.com/r/navidrome/comments/r0lol6/how_to_get_navidrome_to_group_by_album_for/
