### ISSUE TITLE
Songs restarting mid song

### ISSUE THREAD

**Issue by cbounds89** [navidrome/navidrome#1550]
### Description

Listening to a song and then about a minute in the song starts over but the timer does not. 

Is there something I can do to fix this?

### Expected Behaviour

the song to not start over and keep playing. 

### Steps to reproduce

1. play a song in navidrome web page

### Platform information

 - Navidrome version:  0.47.0 8c7d95c1
 - Browser and version: Safari Version 15.3 (17612.4.2.1.2)
 - Operating System: listening on my MacOS 12.2 Beta but naivdrome is running on Ubuntu 20.04.3 LTS  in docker. 

### Additional information

Any other information that may be relevant or give context to the problem.

I don't have this issue if using substreamer. 

Thank you in advance. 

Was watching the log in Portainer while it happened. 
Starting song: 2021-12-31T21:20:28.996170438Z time="2021-12-31T21:20:28Z" level=info msg="Now Playing" artist=AC/DC player="NavidromeUI [Safari/macOS]" title="Track 02" user=cXXXXXX

2021-12-31T21:20:36.869776533Z time="2021-12-31T21:20:36Z" level=error msg="Error sending transcoded file" error="write tcp 172.29.0.2:4533->192.168.1.98:64045: write: broken pipe" id=83b8b5138cf2ff95e6333cd9847ef927 requestId=68576991f081/RqeR3vM8s5-003864

2021-12-31T21:20:50.580865118Z time="2021-12-31T21:20:50Z" level=info msg="Streaming file" artist=AC/DC bitRate=192 cached=true format=mp3 originalBitRate=129 originalFormat=m4a title="Track 02" transcoding=true user=cXXXXX

2021-12-31T21:21:34.821280131Z time="2021-12-31T21:21:34Z" level=info msg="Streaming file" artist=AC/DC bitRate=192 cached=true format=mp3 originalBitRate=129 originalFormat=m4a title="Track 02" transcoding=true user=cXXXXX

Started over here: 2021-12-31T21:22:12.253466652Z time="2021-12-31T21:22:12Z" level=info msg=Scrobbled artist=AC/DC timestamp="2021-12-31 21:20:28.461 +0000 UTC" title="Track 02" user=cXXXXX

2021-12-31T21:22:19.003934333Z time="2021-12-31T21:22:19Z" level=info msg="Streaming file" artist=AC/DC bitRate=192 cached=true format=mp3 originalBitRate=129 originalFormat=m4a title="Track 02" transcoding=true user=cXXXXX

**Comment by niobos** [comment]
I'm having similar issues. Also navidrome 0.47.0 (x86_64) on Debian Bullseye, Safari 15.3 on macOS 12.2.1. Here is some additional information:

Every time this happened and I had the Developer Console open, I noticed that the network request for the media content itself (`/rest/stream?...`) seems to be interrupted, and restarted.

Normally, I see 3 requests per song:
1. A request that Safari shows with status code 0
2. A request for byte range 0-1 with status code 206
3. A request for byte range 0-<total_length>, with status code 206

For songs that restart mid-song, I see:
1. A request that Safari shows with status code 0
2. A request for byte range 0-1, status **200** with complete body
3. A red request for the full file, status 200, but partially downloaded (2.5MB/4.5MB)
4. A red request for the full file, status 200

I couldn't figure out why Safari colors these last two requests red.

I'll try to get some more detailed logging to figure this out, but since this bug doesn't always manifest itself, it's a long journey

**Comment by niobos** [comment]
I've done some more extensive debugging on what I reported earlier. It looks like the problem is related to on-thy-fly transcoding. The few instances where this happened and I investigated it, it were all `cached=false` entries in navidrome's log.

During "restarts mid-song", I see:
1. A Safari network entry for a GET request for `/rest/stream?...`, but with no headers and status code 0. I can't find a corresponding request in the network capture.
2. A GET request for `/rest/stream?...` with `Range: bytes=0-1`. Normally, this is responded with a 206 and the requested 2 bytes. When doing on-the-fly transcoding, the response is a 200 with `Accept-Ranges: none`, `Transfer-Encoding: chunked` and a full body. The download finishes completely in approximately 2.1 seconds and Safari reports 4.37MB received.
3. Before the end of the previous response, there is another GET request for `/rest/stream?...`, colored red by Safari. Here, no `Range:`-header is sent. A similar response to above is sent: 200 with `Accept-Ranges: none`, `Transfer-Encoding: chunked` and a full body. Here, Safari closes the connection during the download. The network capture shows 2378938bytes sent, Safari reports 2.37MB received.
4. Another GET request for `/rest/stream?...`, colored red by Safari. No `Range:`-headers. Response is a 200, but this time with `Accept-Ranges: bytes`. Apparently, the transcode is done by now. Here also, Safari closes the connection during the download. The network capture shows 1512912bytes sent, Safari reports 1.35MB received.
5. ~50 seconds later, another GET for `/rest/stream?...`, colored red by Safari. This time with `Range: bytes=1351707-`. Response is a 206 with `Content-Range: bytes 1351707-4366463/4366464`. Also aborted by Safari during download. Network capture shows 1162496bytes sent, Safari reports 1.10MB downloaded.

The song restarted at about 1m39sec into the song. At the transcoded bitrate of 192kbit, this would translate to ~2.37MB, which would correspond with request 3 above.

Based on the info above, this looks more like a bug in the player instead of the server...

**Comment by deluan** [comment]
Thanks for the detailed investigation. Are you still seeing this issue in the newer version (0.48.0)? Can you try it out with a different web player? Some options:
- Subplayer: https://subplayer.netlify.app
- Airsonic Refix: https://airsonic.netlify.app
- Jamstash: http://jamstash.com

**Comment by niobos** [comment]
I just retried this on Navidrome 0.48.0, Safari 15.6.1 on macOS 12.5.1. I can not reproduce this anymore.

**Comment by niobos** [comment]
I spoke too soon. I just had it re-occur, although it seems less frequent than before.

**Comment by deluan** [comment]
@niobos Can you try with one of the web players above? We need to figure out if the issue is caused by the Navidrome UI or the transcoding engine.

**Comment by niobos** [comment]
I was able to reproduce this with Airsonic Refix (also in Safari) as well.

**Comment by RookieZoe** [comment]
Same issue here, version as shown in the screenshot:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/11600873/236365701-2cb53aef-7f6e-4824-af51-3313e4ecbce1.png">

When transcoding is enabled:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/11600873/236365724-32c62e6b-b48c-424d-89e8-ae471a0858ad.png">

In Safari, player restarts from the beginning halfway through. Subplayer, Airsonic Refix and the built-in UI all have the same problem as shown below:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/11600873/236366282-f4af04e3-9641-4b46-ab36-9041800b4d1e.png">

Jamstash works, but keeps making repeated requests to the stream interface until playback ends. As shown below:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/11600873/236366388-eb40b327-36b5-4914-bd7a-219bdf63806b.png">

**Comment by RookieZoe** [comment]
And I can't see anything from the request:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/11600873/236366941-dc3a9c1b-66cf-427b-a61c-64e96974687d.png">
