### ISSUE TITLE
Add more details to FLAC file quality on the table (like MP3 320)

### ISSUE THREAD

**Issue by Extarys** [navidrome/navidrome#1571]
### Is your feature request related to a problem? Please describe.

[This is very low priority]

I have many flac files. Some of them are ripped from my cassettes, some are from 7digital, bandcamp, CD, etc. 
Currently when I search for a song, I might have it once in mp3 from the old days, a FLAC from a physical CD and a Hi res flac from 7digital. This would allow me to easily pick the quality I need in a convenient way.

If I'm using my phone's speaker for example I can just pick whatever, but if I'm on my couch with my nice headphones I might pick a better one for example.

Since it's easy to spot MP3 quality, it would be only fair if we could do the same with FLAC :smiley_cat: 

### Describe the solution you'd like

I have two solutions to propose on top of my head:

Either add some dots or marker to differentiate better quality files. Hovering the FLAC label could show the khz/bit.
![image](https://user-images.githubusercontent.com/11581433/149438381-c39d8012-37da-4159-8dc1-b839c0cacb56.png)
(Easy html editing, they could be bigger/bolder XD)

Or just plain add "FLAC 48k/16", but it might be too wide. Right now the longest I saw is "MP3 320"
![image](https://user-images.githubusercontent.com/11581433/149438550-1d2e9a4f-c51c-49bf-b923-307fabc155e1.png)

I also thought about using colors, but colourblind people would still need an easy way to see the file quality... :/

**Comment by certuna** [comment]
There's already been some discussion on it - there are a number of attributes Navidrome can store/display: codec (MP3/AAC/FLAC), bitrate (128/192/320 kbps), channels (mono, stereo, 5.1), bit depth (16/24 bit) and sample rate (44.1/48/96 kHz). Difficulty is finding an space-efficient and aesthetically pleasing way to display it, since we want to keep the UI as clean as possible.

My current ideas on this are:
- lossy formats (AAC/MP3/OGG): codec + bitrate + channels if they're not stereo ("AAC 5.1 256", "MP3 320")
- lossless formats (FLAC/ALAC/DSD): codec + channels if not stereo + bit depth if not 16-bit, sample rate if not 44.1 kHz + ("ALAC", "FLAC 24/96", "DSD 5.1")
- display a little "HD" icon behind the album name if the album contains HD material (>16 bit or  >44.1 kHz)
- filter in the album list/grid view: probably best to only have a "HD/All", for more granular filtering smart playlists are probably better

**Comment by TheWrathKing** [comment]
@certuna When you say "in lossy formats the concepts of bit depth and sample rate don't exist", while this is almost true 99% of the time, MP3 can be encoded (via lame for example) with a sample rate of 48 Khz.

**Comment by certuna** [comment]
@TheWrathKing of course you can use 48 kHz as source material, but mp3 (like all lossy formats) transforms the audio from the time domain into the frequency domain (FFT), where the concepts of "sample rate" and "bit depth" don't exist. You cannot detect from an mp3 file what sample rate/bit depth the original source material was.

@Extarys vinyl rips can be tagged (and potentially, read/used by Navidrome) using the `TMED`/Media Type tag: https://github.com/navidrome/navidrome/issues/1036 , this is another metadata enhancement that could be added.

**Comment by certuna** [comment]
Still relevant & valuable, on my To Do list
