### ISSUE TITLE
Keyboard/remote control navigation

### ISSUE THREAD

**Issue by andrewshadura** [navidrome/navidrome#1572]
As an Android TV user, I want to be able to navigate the UI with the remote control, so that I can comfortably browse the music library without having to connect a mouse or buy a touch screen.
Similarly, as a user of a laptop, I want to be able to use Tab, arrow keys and other shortcuts with Navidrome, so that I don’t have to use the mouse or a trackpad or a trackpoint.

At the moment, Navidrome doesn’t offer this in a usable way: while Tab allows jumping between elements, it goes through all clickable things, requiring too many presses to do anything useful. Arrow keys work during the playback, but I cannot start music from the album list.

Optionally, controlling the UI in this way can be a separate mode.

**Comment by metalheim** [comment]
Having recently bought an android tv as well I like the idea. 
"d-pad" navigation in the webui should improve/enable usability on all kinds of devices (tvs, game consoles, TV boxes etc.)

But a UI that works nicely on limited input devices should be more than "just" the normal interface with "d-pad" navigation.
F. E. https://subfiresuite.com/SubFire2TV handles this well with an UI that's specifically tailored for TV use.

Maybe worth trying for you as well?
Since you have an android tv, you could also "cast" from your phone, f.e. With the "dsub" app or "substreamer"

**Comment by andrewshadura** [comment]
Yeah, I tried casting from DSub today, it worked but was missing a bunch of things.
SubFire — wow, it’s impressive, but… the author doesn’t seem to want to make it open source?

**Comment by andrewshadura** [comment]
Please remove the stalebot.

**Comment by andrewshadura** [comment]
Why? 😕

**Comment by deluan** [comment]
@andrewshadura 

Sorry for letting this be closed. The main use-case for Navidrome's UI is for desktop usage. It also tries to cater for moderate mobile usage, with some limitations.

For connected devices like Android/Apple TV, a proper solution is to have a dedicated client, built for that platform. 

It is really hard to make the web UI works on all possible platforms/displays, so the focus will remain desktop (web) and some mobile support.

If you like SubFire, even if it is not open source, I think it is a valid option. Not all software we use on our day to day are open source, right?
