### ISSUE TITLE
[Feature Request] Video support (Concerts, Tapes, Bootlegs)

### ISSUE THREAD

**Issue by Pheggas** [navidrome/navidrome#1598]
### Is your feature request related to a problem? Please describe.
Yes actually, i can't watch concerts and live performances that i have saved locally of my fav artists.

### Describe the solution you'd like

A clear and concise description of what you would like to happen.

Add video support in style like Plex has. When you open some artist, you see albums in panes and under it are those live performances and concerts. Each have it's tag if it is life performace or music video or whatever.

Take a look:
![image](https://user-images.githubusercontent.com/9994511/152521876-e03af769-4db9-4454-b3b2-293e18ae15dd.png)

### Describe alternative solutions that would also satisfy this problem

There's no clear alternative (or at least i don't know any)

### Additional context

Might add frontend visualization later.

**Comment by GlassedSilver** [comment]
I hope it's not rude to hijack this issue and extend on the thought a little bit:

Bonus if there is a way to also be able to assign an audio-only music item.

That can be the extracted audio track, but sometimes isn't, for example when the music video to a track has extra segments like intros making it longer and sometimes even slightly different. (intermissions being another possibility)

I listen to a lot of nightcore music remixes, to me the visualization videos are part of the fun, so having an audio-only associated file would be handy for two reasons: quick and easy switching between streaming the video and streaming audio-only, for example on a smartphone with background playback and the screen off.

But also this link would be handy so that plays count towars the track, no matter the split between video and audio.

I don't remember the software that worked similarly to that, but this fusion of audio-only and videos has been done before and ever since I witnessed that magic that's one of the first things I look for in a software.

(I guess on a related note the same backend logic for that could be used to count plays of the same track that lives in more than one album towards both as well?)

Cheers!

**Comment by deluan** [comment]
Thanks for trying Navidrome! Unfortunately, supporting video is way beyond the scope of Navidrome. There are great video servers out there (including Plex, Emby, Jellyfish...), so I don't think it is worth spending time trying to compete with them, specially when there's clearly a lot of improvements that can (and need to) be done in Navidrome as a music server.

**Comment by GlassedSilver** [comment]
I'm aware of the alternatives that you mentioned and yet here I am...

If Jellyfin has offline-support with sync-back of play counts and such maybe I wouldn't ask for that here, but scope was the catchphrase there as well. :,D

Maybe I just have to live without offline-sync of music videos and having them live in awkward separation to the rest of my music. ;__;

Maybe another time, maybe opening up ports like a madman or constantly forcing my phone to connect to home with a VPN is expected these days. I don't like the threat surface, but oh well.

Sorry if I sound sour. As for Plex and Emby... I have a PlexPass Lifetime, but I'm not putting my media library into a non-FOSS project again like that. I got burnt multiple times before, mostly by Apple, and it's not a fun experience when company and user interests drift apart. No source code means the entire software goes a different direction without forks having a chance to correct course.

**Comment by wigust** [comment]
Hello.

I have music as video clips.  It's not convinient to store video and audio separately, which requires either to split them or store them twice.

Could navidrome treat video as audio (play audio from video file), without changing the web interface and user current experience?  Is "Transcoding on the fly" feature able to provide that?

Thanks.

**Comment by GlassedSilver** [comment]
> Hello.
> 
> I have music as video clips. It's not convinient to store video and audio separately, which requires either to split them or store them twice.
> 
> Could navidrome treat video as audio (play audio from video file), without changing the web interface and user current experience? Is "Transcoding on the fly" feature able to provide that?
> 
> Thanks.

It's not just not convenient, it doesn't even make sense to have different "homes" for music videos and music as audio-only tracks.

I forgot which software or service it was that offered this, but my dream remains to be able to link an audio-only track to its music video counterpart, so I can toggle a playlist to play in music-only mode or music video mode where tracks that miss a music video are just visualized with stuff like spectrum visualization and such. Maybe with backgrounds either in random or à la carte per track.

This visualization in the style of all those night core music remixes on YouTube.

That's my dream goal for my music collection.

**Comment by Pheggas** [comment]
What I see so far, video support isn't way beyond scope of this app. Video playback was part of music since analog cameras were made. I can mention some examples like MTV or nowadays YouTube and other platforms. There are surely many people that want this feature in Navidrome to be able to fully switch to it and use nothing else. I'm currently using Plex server as my media provider and the only thing backing me off from switching to Navidrome is actually video playback.
