### ISSUE TITLE
Navidrome behind Haproxy configuration not working

### ISSUE THREAD

**Issue by nonyhaha** [navidrome/navidrome#1615]
### Description
Hello.
I have Navidrome installed on a ubuntu server on which I am also running Nextcloud.
This is a vm on an esxi host. 
On another vm I have a firewall with haproxy and letsencrypt. This serves a few servers on the network without issues. 
I am trying to redirect a new subdomain to the Ubuntu server's IP:4533 (navidrome) but it is failing to be accessed from outside local network.

### Expected Behaviour

It should work

### Steps to reproduce

My navidrome.toml file:
```
MusicFolder = "/mnt/Muzica"
ScanSchedule = "0"
LogLevel = "info"
Port = "4533"
AuthRequestLimit = "3"
AuthWindowLength = "30s"
EnableUserEditing = "true"
ReverseProxyUserHeader = "Auth-User"
#ReverseProxyUserHeader = "Remote-User"
ReverseProxyWhitelist = "firewall/haproxy's IP"
#Address = "localhost"
```
I have tried with the following:
ReverseProxyWhitelist = "0.0.0.0/0"
Either auth-user or remote-user for ReverseProxyUserHeader
I believe it is a problem with the Address section. If I put anything besides it's local vm IP it will not work even locally.

### Platform information

 - Navidrome version: [0.47.5] (86fe1e3b)
 - Browser and version: Chrome, Firefox, Edge
 - Operating System: Ubuntu 20

**Comment by niobos** [comment]
I have a very similar setup (HAProxy -> Navidrome, but on Debian instead of Ubuntu), and it works here.

Since your HAProxy runs on a different VM, you definitely need to keep the default `Address` config (i.e. `0.0.0.0`/`::`), otherwise HAProxy will not be able to connect.
In my setup, I don't use any `ReverseProxy` config, since I authenticate directly to Navidrome, and not to the proxy.

Can you try again without `ReverseProxy` and `Address` statements in your config? If it doesn't work, please report the exact error you are getting: is it an error from HAProxy? Or from the browser? Do you get the error immediately? Or after a few seconds?

**Comment by nonyhaha** [comment]
Hello. 
I forgot to post here also, I am sorry. 

It turns out new browsers will not allow connection to a server if the certificate is not correct. 
I did not have the certificate updated on my machine, and it did not allow me to load the page. 
I know in the past I could browse pages without the certificate being updated, but not anymore. 
Anyway, It is working flawlessly!

**Comment by niobos** [comment]
Great to hear it works now. Please consider closing this issue!
