### ISSUE TITLE
Three meanings of the X button

### ISSUE THREAD

**Issue by hboetes** [navidrome/navidrome#1644]
The user interface here is a bit inconsistent:

![image](https://user-images.githubusercontent.com/2285225/156946052-f546f08c-1bad-4873-b01b-4614192d56a2.png)

The top X means: close window
The playlist X means: remove track
The bottom X means: remove all tracks

I propose using the dustbin when it means remove track(s) and X when it means close window.

Of course even more elegant solutions are welcome.

**Comment by hboetes** [comment]
Yes, I still think this is relevant, and since I got 5 thumbs up I would really like it if the devs have another look at this issue.

Thanks!

**Comment by freshgum-bubbles** [comment]
I think a minus would make more sense for removing individual items from the queue.  Furthermore, perhaps the top X on the queue could be a downwards-facing arrow?  This would make more sense IMO, as it accurately portrays where the element would "go".  

An example of this is YouTube Music, which uses the downwards-facing arrow to allow the user to expand or minimise the now playing & queue screen.
![image](https://github.com/navidrome/navidrome/assets/85623267/1bbba12d-1b8f-4d89-b11b-c050d5d9fa77)

**Comment by deluan** [comment]
I agree that this is not great from UX perspective. This is a result of using an external player (not created for Navidrome) with a different look and feel than Material-UI (used by ND).

Sorry, but this won't be "fixed" because this player is [unmaintained](https://github.com/navidrome/navidrome/issues/1651) and we plan to introduce a different player (#2285) with the new UI.
