### ISSUE TITLE
Sonos support

### ISSUE THREAD

**Issue by Ch00k** [navidrome/navidrome#165]
Is there a plan to support Sonos integration, like Subsonic does?

**Comment by deluan** [comment]
That would be great, but I don't have plans for that right now. Contributions are welcome :)

**Comment by patsaindon** [comment]
Sonos use Subsonic API to access the music library.  Look at the link http://www.subsonic.org/pages/sonos.jsp.

**Comment by SteveDinn** [comment]
> Sonos use Subsonic API to access the music library. Look at the link http://www.subsonic.org/pages/sonos.jsp.

I don't think that's what that link implies. I believe Subsonic is especially supporting Sonos speakers. Otherwise, the configuration would be on Sonos' end, not Subsonic's.

**Comment by deluan** [comment]
@SteveDinn , that's my understanding too, but I didn't spent too much time figuring this out yet.

**Comment by patsaindon** [comment]
@deluan You can find the info here. https://musicpartners.sonos.com/node/72

**Comment by JannesMeyer** [comment]
I would be curious about this, too. On the sonos devices you can register yourself as a "music service" which is then shown in the Sonos Controller app.

The latest documentation is available here: https://developer.sonos.com/build/content-service-get-started/test-your-content-service/

To register the service you have to fill out a form on any of your Sonos devices: `http://$SonosDevice:1400/customsd.htm` where `$SonosDevice` is the IP address of one of your Sonos speakers. I think Subsonic automatically submits this form (HTTP POST) in an attempt to register itself.

**Comment by MoralCode** [comment]
would a library like https://github.com/ianr0bkny/go-sonos help make this easier?

**Comment by deluan** [comment]
Hey @MoralCode, we don't have any development specific documentation, but I'd be glad to answer any questions and provide any needed guidance over Discord.

**Comment by MoralCode** [comment]
To summarize from the discord conversation:

It seems like the consensus is that this fits in really well as part of a broader "playback services" milestone with other issues like #364 (jukebox), Alexa integration (from GSOC page),  #682 (google home) .etc.

It also seems like the current working idea for the best way to implement this for all of the various external playback mechanisms is for the navidrome server to act as a kind of the main hub/controller for all playback to "external" sources (i.e. all the ones that arent going through a subsonic client). In this model the server would have one or more queues for the currently playing songs on each of the various external services (sonos/google home/whatever) and sends commands to these services/devices. Since the server is pretty much always online, this allows the server to instruct these devices to play the next song in the queue as the last one ends without the client device's presence being required to instruct it to do so (helpful in cases where the phone goes to sleep). 

The jukebox aspect of this seems to have API support using the [/rest/jukeboxControl endpoint](http://subsonic.org/pages/api.jsp#jukeboxControl), but it is meant to be used only for the jukebox (server's audio device). Since the subsonic UI controls playqueues in a different way, not using this API call, this functionality will likely need to be re-implemented in a similar way in Navidrome's UI/API. This could even allow ND to implement the MPD protocol, and leverage MPD clients

It seems as though alexa, Google home, Sonos, .etc all operate in a similar way in that theres some component that issues a command to the device to tell it to play a particular piece of media, and then the device itself requests the content directly from the server at the path identified by the url/identifier provided in the initial command 

as it relates to sonos specfically:

In the [sonos model/architecture](https://developer.sonos.com/build/content-service-get-started/architecture/), the controller is - i believe- anything that implements the sonos controller API. This controller essentially just tells sonos player to "play this stream", "pause" .etc.  Examples of this include the sonos app, the soco-cli python package i was using for a [previous sonos project](https://github.com/MoralCode/sonos-bt-speaker).

Since there is a library (that I linked above) that might implement this controller API in go, the first order of business on this is figuring out how to create a stream/endpoint that is Sonos-friendly (in terms of required parameters, authentication, [supported formats](https://support.sonos.com/s/article/79?language=en_US) etc), and registering it in the device (using the [internal form as per the Subsonic docs](http://www.subsonic.org/pages/sonos.jsp)) so it can be played by a player when it receives the instruction from the controller.

here are some additional useful pages form the sonos developer docs with some diagrams on how things work:
[playback on sonos](https://developer.sonos.com/build/content-service-get-started/playback-on-sonos/)
https://developer.sonos.com/build/content-service-get-started/play-audio/

the [sonos reference page on the authorization API](https://developer.sonos.com/reference/authorization-api/) may be helpful in figuring out what to do in terms of auth, although in my experience with `soco-cli`i was able to get an mp3 stream to play without having to provide any auth information to sonos so this may not be necessary and may depend on which of the sonos API's from that reference page are used

**Comment by MoralCode** [comment]
upon some further ~~messing around~~ testing, sonos is able to play an mp3 stream just by grabbing the stream URL from inspect element in the web UI, setting the `format` (see docs [here](http://subsonic.org/pages/api.jsp#stream)) to `mp3` and instructing the sonos to play that stream url using soco-cli.

It seems like this method only supports mp3, WMA,and AAC/HE-AAC (per the [sonos docs](https://support.sonos.com/s/article/79?language=en_US)). This audio playback may also break if the auth information provided in the URL gets refreshed/reset.

**Comment by legobuild** [comment]
While I can't offer any help, count me as another user interested in Sonos integration. I currently have home audio set up through several airport expresses and use Logitech Media Server to access my Navidrome library and serve it to different rooms. I'm considering migrating to Sonos and would look at access my library directly from the Sonos app.

**Comment by simojenki** [comment]
I wrote the following project -> https://github.com/simojenki/bonob to integrate sonos with navidrome via the subsonic api.    
I don't have the bandwidth rewrite it in golang within navidrome itself,  however if someone else would like to embark on that bonob would serve as a reasonable working example, there are plenty of tests that demonstrate how sonos -> 'service' integrate, and I'm happy to answer any questions based on my understanding of what needs to be done.

**Comment by deluan** [comment]
This is awesome @simojenki, thanks for sharing! This will be definitely helpful when implementing Sonos support!

**Comment by MoralCode** [comment]
@simojenki wow this is awesome! I'll see if I can spend some time turning this into a standalone go library/module that could be used by Navidrome and other go apps

**Comment by legobuild** [comment]
This is great @simojenki. I was able to set up your project this afternoon with no issues. Navidrome serving up to my Sonos Five now. Still need playlist support, but so far this works great.

**Comment by simojenki** [comment]
@legobuild  playing of playlists has been added (to bonob), so try now.  Editing playlists will require some time as that is a different usage of the sonos smapi api.

**Comment by legobuild** [comment]
> @legobuild playing of playlists has been added (to bonob), so try now. Editing playlists will require some time as that is a different usage of the sonos smapi api.

I just updated and it works perfectly. Thanks!

**Comment by deluan** [comment]
Thanks @simojenki It works like a charm! By the way, are you in our Discord? I have some questions regarding the implementation. Ex: Is it possible to host bonob in a server outside your local network? In that case how bonob will register with the speaker?

**Comment by simojenki** [comment]
Just joined discord.

**Comment by certuna** [comment]
Ah no Opus then.

**Comment by simojenki** [comment]
You would need to transcode into something else

**Comment by kaosnews** [comment]
Wait... are we getting Sonos support? Oh wow!

**Comment by deluan** [comment]
Closing this as it is now well supported by bonob, and I don't have plans to incorporate the functionality in Navidrome for now.
