### ISSUE TITLE
Group all songs in 1 Album and not split them apart specially if the tracks are with different artist

### ISSUE THREAD

**Issue by remlei** [navidrome/navidrome#1664]
### Is your feature request related to a problem? Please describe.

Viewing Albums with tracks performed by different artist.

what happen here is every artist have its own group of the same album.

so lets say i have 12 tracks on that album performed by 12 different artists, you will see 12 variations of that same album separated by artist,  I want to play all of this track as a album, not by artist.

yeah sure I can create a playlist for this but....

### Describe the solution you'd like

View all of this track with different artist in 1 album page.

### Describe alternative solutions that would also satisfy this problem

Create a Playlist...

**Comment by jan666** [comment]
I think you should read https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

**Comment by zajnemzaj** [comment]
I also opened this issue and also was redirected to this telling that this is a feature.

Forcing users to re-tag more ten thousands of mp3s is not the best idea I guess.
Still see no reason why mp3-s tagged with same album name shouldn't be displayed in one place.

At last it might be a good idea to open a feature request to be able to switch between these display options.

**Comment by jan666** [comment]
> Still see no reason why mp3-s tagged with same album name shouldn't be displayed in one place.

I once opened an issue to request the opposite of this. My reason is: sometimes there are artist that have 2 "albums" with the name name. Exmaple: https://musicbrainz.org/artist/0c8e3043-7b42-4a97-9917-a57e9116cf6f the demo from 1986 and the album from 1991 have the same title. So in navidrome its one album. But this is wrong. 

And even worse: if you don't use the artist too you will group albums from different artists that have the same title.

IMO it's great the "Part Of Compilation" tag exists and you should really use it.

**Comment by zajnemzaj** [comment]
I am really happy that "Part Of Compilation" tag exist to avid the same album name problem which I have never had so far. 

But I have more ten thousands of mp3-s without that special tag used and no time to re-tag those compilation or split albums one-bye-one.
It will come up again and again for new users anyway.

Being able to switch between these view modes under list/grid switch in album view, could make this problem non-exist.

**Comment by jan666** [comment]
> I am really happy that "Part Of Compilation" tag exist to avoid the same album name problem which I have never had so far.

No it does not solve my problem. My problem still exists. I just used my problem as an example to show you that "just use album tag" is not a good solution.

**Comment by remlei** [comment]
this is unfortunate, from what I read from you guys, this is more likely a feature from what you guys said, but damn, its really hard to listen to tracks this way.

I guess im back to UPnP again, The only issue I had with UPnP  is its taking a minute or two to list all 500+albums that I had, this one is listing all the albums properly. 

But navidrome is actually makes it really inconvenient for me to listen to my music library. Majority of the Listed albums in my case is very fragmented, I can safely say that 70% of  my library have this "Splitting Album tracks by artist" kind of issue.

**Comment by deluan** [comment]
Implementing this is a double-edge sword. As @jan666 mentioned, ignoring the "part of compilation" or the album artist tags can make things even worse for people that wants a more detailed library. And it can also cause issues with same name albums as described in an old GH issue opened about this: https://github.com/navidrome/navidrome/issues/622#issuecomment-770549703 (look at the screenshots).

One of the principles of the project is "tags are the source of truth", so we avoid as much as possible reading metadata from  the directory structure or any sidecar files. I know that saying "just fix your tags" may sound harsh and insensitive, but look at the bright side: this is something that will make your library more compatible with other softwares in the years to come, there are other servers and players that also handle music files like this, only by tags. I personally had to curate the tags of my 70K+ library, I know it can be a pain, but the end result is worth it.

The only thing I can try to do, and I'd like to stress that I'm **not** making _any_ promises here, is to try to implement a configuration flag that forces Navidrome to group songs by folder and not by the album tag, which would most probably solve the issue for the majority of the cases. I'm not promising it because this may be harder to implement than it sounds.

Old discussions about this topic:
- https://github.com/navidrome/navidrome/issues/622
- https://www.reddit.com/r/navidrome/comments/r0lol6/how_to_get_navidrome_to_group_by_album_for/

**Comment by jcjordyn130** [comment]
I read the wiki page about the topic and I noticed it mentioned the compilation tag, is the ensemble tag considered part of the FLAC/Vorbis Comments standard?

**Comment by thias** [comment]
I ran into this issue too when I started using Navidrome. Compilations, mix albums, albums with a bunch of "x Feat. y" as the artist, etc. would all result in multiple entries of the same album, once for each "artist".

My first reaction was to be annoyed, like many others.

But after I understood the "problem", what I did was just slowly go with the minor cleaning up of my tags: Each time I'd encounter such an "album" while browsing my library, I would add the Album Artist or the itunescompilationflag 1 as needed (I use puddletag on Linux). The great thing about navidrome is that it can pick up library changes very quickly, you just need to sometimes move the album away and back to work around scan race conditions (at least in my case), but overall you can very quickly clean things up in a way that makes a lot of sense and won't break with other players or library managers.

I now have a much cleaner music library, and navidrome actively helped me get there! I suggest you bite the bullet and do the same, your future self will thank you for it! :smile:

**Comment by remlei** [comment]
the problem is, I have a big library, if this issue only affects like a few
20-30albums, yeah sure... but this affects basically 70% of my library and
that hundred (or thousands of files) that I need to re-organized maybe for
the third time.

so, nope, ill probably just stop using this and keep using plex.
