### ISSUE TITLE
Support .dts and .aac audio files

### ISSUE THREAD

**Issue by fengwang** [navidrome/navidrome#1678]
### Is your feature request related to a problem? Please describe.

I have quite some music which are '.dts' and '.aac' format. But navidrome is not able to handle them.

### Describe the solution you'd like

I can see ffmpeg is used as transcoding backend from Settings -> Transcoding menu.
Maybe it is not that difficult to support '.dts' and '.aac' files in the same way that '.flac' files being supported.

### Additional context

A typical '.dts' file report from my Music library:

```
$ ffprobe  '11.领悟(陈影).dts' 
ffprobe version n5.0 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[dts @ 0x5646f7724fc0] Estimating duration from bitrate, this may be inaccurate
Input #0, dts, from '11.领悟(陈影).dts':
  Duration: 00:04:09.52, start: 0.000000, bitrate: 1411 kb/s
  Stream #0:0: Audio: dts (DTS-ES), 44100 Hz, 6.1, fltp, 1411 kb/s
```

**Comment by certuna** [comment]
DTS and AAC streams are almost always used inside an MP4 container, you can mux them into their correct container with: `ffmpeg -i audio.aac -c:a copy audio.m4a`

**Comment by fengwang** [comment]
> Raw DTS and AAC streams are almost always used inside an MP4 container, you can mux them into the container with: `ffmpeg -i audio.aac -c:a copy audio.m4a`

Many thanks for the suggestion. 
But I have collected more than terabytes of music, and converting it to another format is not cheap.
Or maybe supporting more formats in navidrome is more complex than what I expected?

**Comment by deluan** [comment]
Sorry for being late.

As @certuna noted, this would cause Navidrome to show songs without any metadata (`Unknown Album/Artist`). Because of that, I don't think we should support raw audio streams.

@fengwang as you can see from the `ffprobe` output you posted, there's no metadata in your file. If you are ok with having a bunch of files without any proper information in Navidrome, you could change that `mime_types.go` file and recompile Navidrome. It would pickup all files with those extensions and try to extract info from them using whatever extractor you are using as defined by the `Scanner.Extractor` config option (default `taglib`, but you can switch to `ffmpeg` which support more filetypes)

Closing this now, but feel free to chime in if you still have any concerns.
