### ISSUE TITLE
Maximizing player icon not working on mobile web UI

### ISSUE THREAD

**Issue by snowphone** [navidrome/navidrome#1786]
### Description

On a mobile web UI, it fails to maximize a player. I recorded the bug, so watching it would be much clear.

### Expected Behaviour

Now-playing is maximized.

### Steps to reproduce

1. Open web UI on a mobile phone (e.g Galaxy S10e) with samsung internet or chrome, but not firefox browser.
2. Play any songs.
3. Close the player to make it minimized.
4. Try to click minimized player button to re-maximize it, but it'll fail.

### Platform information

 - Navidrome version: 0.47.5
 - Browser and version: Samsung internet v17.0.6.9 and Chrome, but not firefox on Android 12, Galaxy S10e (client-side)
 - Operating System: Ubuntu 20.04 + official docker (server-side)

### Additional information

https://user-images.githubusercontent.com/23140464/175777516-19210fdc-8ece-4a70-8f6b-840a86439b12.mp4

**Comment by Dnouv** [comment]
Hello @snowphone 
Thank you for reporting the bug, the player has been quite buggy for a while, and there are plans on the roadmap, to replace it with a Navidrome-specific built player. But there has been a long delay due to the busy schedules of the members, and the lack of developers to contribute. So please wait a while, it should be launched soon. 
If you feel like you could contribute and would be able to commit time, please hop on to Navidrome's Discord server, any contributions are welcomed.

Thank you!
