### ISSUE TITLE
iOS devices don't play next song when screen is locked

### ISSUE THREAD

**Issue by ebiscaia** [navidrome/navidrome#1802]
### Description

If I start playing an album or playlist on an iPhone and I lock the screen the song is played till its end and doesn't go to the next one. I have to make it play manually every time a song finishes.

### Expected Behaviour

Song finishes and start a new one with the screen locked without the need of user intervention.

### Platform information

 - Navidrome version: latest
 - Browser and version: ios Safari
 - Operating System: ioS latest version

Thanks,

Eduardo

**Comment by mattneub** [comment]
This seems like a normal behavior of Safari, and not something having to do with Navidrome at all. Solution: use a dedicated player app such as Play:Sub.

**Comment by certuna** [comment]
This is indeed caused by Safari not executing regular JS code when it's screenlocked, but: I think we can implement the service worker (which is meant to stay active when the PWA is minimized) to queue up the next track.

Unfortunately I'm not good enough to implement this myself, but if you know anyone with experience with JavaScript service workers can help us out, that would be great.

**Comment by ebiscaia** [comment]
Hi,

I installed Amperfy and it is working fine.

Thanks,

Eduardo
