### ISSUE TITLE
Extract artist artwork from embedded images

### ISSUE THREAD

**Issue by Igorgro** [navidrome/navidrome#1869]
### Description

Navidrome selects wrong cover from FLAC files. When there are two coves in the FLAC file: the front album art and the artist art, Navidrom selects artist art cover and shows it as the album art in the interface. This only affects FLAC files and not the MP3 files.

### Expected Behaviour

The front album art cover is selected as the album art in the interface

### Steps to reproduce

1. Upload an album of the FLAC files which contains two covers: album art and artist art
2. Open album in the Navidrome web interface
3. See wrong cover is seleted from the FLAC files
### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: Google Chrome 105.0.5195.102, but not sure that this matters
 - Operating System: Debian 11, native Navidrome installation

### Additional information

See attached screenshot:
1. The first album is MP3 and it contains both front cover art and the artist art and everything here works well
2. The third album is FLAC and contains only front cover art and everything is ok
3. The second and the fourth albums are FLAC and contain both front cover art and the artist art and this is where the bug behavior appears
4. (Not sure if it is another bug) Does the artist art should appear instead of big grey star at the top of the screenshot?

 - Screenshots (please remove if this is a copyrighted content, it is used only for demonstration purpose):
 
![image](https://user-images.githubusercontent.com/22894169/189537070-11d0e3b4-d5e3-4cab-86a0-64b6f1cae9cd.png)

If it may help somehow I can email this FLAC files to those who wants to reproduce this bug.

**Comment by Vista2003** [comment]
The grey star is a placeholder when Navidrome can't get an artist photo. You will need to connect your Navidrome to Last.FM or Spotify for the star to actually show an artist (if the artist is on those platforms)

**Comment by Igorgro** [comment]
Why not to extract it from meta info?

**Comment by Vista2003** [comment]
Because an artist photo doesn't exist in the metadata

**Comment by Igorgro** [comment]
If so, why can I set it for example in Kid3?
![image](https://user-images.githubusercontent.com/22894169/191198798-7095c190-5d5b-4893-ac41-c1b00f66a56c.png)

**Comment by metalheim** [comment]
You can attach Artist pictures in metadata, but its not currently read out by navidrome, nor used in any other fashion.
For background information, theres lenghty discussions about how to fetch artist images in issue #394 

Currently, navidrome can only get artist images from metadata provider spotify. This needs a spotify (free or paid doesnt matter) account and the apikey need to be configured in navidrome.

**Comment by Igorgro** [comment]
> but its not currently read out by navidrome

But why does this bug (which described in the issue) persist?

**Comment by Vista2003** [comment]
> > but its not currently read out by navidrome
> 
> But why does this bug (which described in the issue) persist?

To me, this doesn't seem like a bug, it seems more like a lack of a feature probably because it's easier to use someone else's service to pull that data and there are more higher priority things that need sorting first.

**Comment by Igorgro** [comment]
Well, if you read carefully it is not about a gray star, but rather abut wrong selection of album art from flac files

**Comment by crazygolem** [comment]
I investigated this issue a few weeks ago. The problem is that navidrome currently doesn't mapping support picture types, and will just request any image from the underlying library.

For MP3s, the underlying lib returns the first image in the data stream, but for some reason for FLACs it will return the last one.
It is just a coincidence that nobody noticed for MP3s yet; I assume that most people add the cover picture before the other pictures when they tag their collection.

So a quick workaround would be to reorder the pictures in the FLAC file's data stream, and insert the "main cover" last so that navidrome picks it up when displaying covers. If your tagging software doesn't allow to reorder pictures (and I don't know of any that does), you'd have to delete all of them, and then re-add them in the desired order (I tried it out with mp3tag).

Ironically, adding support for artists' pictures from tags will also likely solve this issue, as it will likely have to be done by adding support for mapping picture types as suggested in https://github.com/navidrome/navidrome/issues/394#issuecomment-799501347

**Comment by deluan** [comment]
Both `ffmpeg` and `taglib` supports multiple embedded images. Ex output from `ffmpeg`:
```
  Duration: 00:04:13.96, start: 0.000000, bitrate: 831 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Side data:
      replaygain: track gain - -6.080000, track peak - 0.000021, album gain - -6.080000, album peak - 0.000021,
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 953x953 [SAR 200:200 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
  Stream #0:2: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 742x743 [SAR 72:72 DAR 742:743], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Artist/performer
      title           : 0019905298_10.jpeg
```

Unfortunately, they are only used to _detect_ the presence of embedded images, not to extract them. The https://github.com/dhowden/tag package, used extract embedded images does not support it, and returns a random one if there are multiple images.

The solution would be to start extracting images using `taglib` and/or `ffmpeg`, and store their references in the DB. But unfortunately I don't have bandwidth to work on this right now.

**Comment by Igorgro** [comment]
Please, don't close this!

**Comment by Mladia** [comment]
The issue is that the embedded images are not handled properly.

### Example 1:
foobar:
<img width="409" alt="image" src="https://github.com/navidrome/navidrome/assets/15912404/8888ed5b-ac59-44ff-946f-02e8c45cee91">
Navidrome:
<img width="391" alt="image" src="https://github.com/navidrome/navidrome/assets/15912404/49cb68dc-85a1-462c-a5a7-6593c92688a9">

**Actual:**
The artist icon is spinning beside Now Playing instead of the disc icon,
The artist icon is empty:
<img width="401" alt="image" src="https://github.com/navidrome/navidrome/assets/15912404/4eb240bd-7404-42c9-ab8f-230ecad28ac8">


### Example 2:
foobar:
<img width="407" alt="image" src="https://github.com/navidrome/navidrome/assets/15912404/e47e2058-1630-42b4-b209-dab702336272">
Navidrome:
<img width="372" alt="image" src="https://github.com/navidrome/navidrome/assets/15912404/d9af21be-833c-4788-ac0f-b0e0e364da07">
**Acutual**
The Disc icon is displayed as Front cover (and also spinning besides Now Playing which is actually correct)
