### ISSUE TITLE
No .m3u playlist found after first scan

### ISSUE THREAD

**Issue by FunDeckHermit** [navidrome/navidrome#1881]
### Description
No playlist was shown in the UI after the initial scan. The Debug logs clearly state that the playlist was found. Didn't try trace...

### Expected Behaviour

The playlist being loaded. 

### Steps to reproduce

Music folder with about 100 files and a playlist (.m3u) file with all those files. 

1. Delete data folder contents
2. Docker compose up --force-recreate

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Some Brave version
 - Operating System: Docker

### Additional information

Fixed it by editing the .m3u file, giving it a new timestamp. Navidrome then found the playlist.

**Comment by deluan** [comment]
Sorry, but I was not able to reproduce it locally. I would help to have a trace log.

**Comment by RandomBloke85** [comment]
I have the same behaviour. No playlists visible although path to
`PlaylistsPath = "./Playlists/"`
v0.48.0, all playlists are *.m3u and this worked flawlessly  in v0.40 in FreeBSD. Now I'm on ubuntu Server 22.04

Otherwise couldn't be happier with Navidrome - fantastic piece of code. Thank you so much for this!

**Comment by RandomBloke85** [comment]
Tried to give it a new Timestamp too, but without success. Btw, I followed the installation guide for Linux on navidrome.org. Could it be a permission issue?
