### ISSUE TITLE
add suppot for webm audio format

### ISSUE THREAD

**Issue by jkumeboshi** [navidrome/navidrome#1927]
webm audio format is the default YT by now and it would be nice to support it without the need to convert it before adding it in the Navidrome music folder

**Comment by certuna** [comment]
If I'm not mistaken, the WebM container is not supported by TagLib (which is what Navidrome uses to read tags), so you'd have to add support for the format there: https://github.com/taglib/taglib

**Comment by deluan** [comment]
> it would be nice if navidrome had some xml/json-fallback

@tamaskan What do you mean?

@jkumeboshi I did some testing downloading stuff from YT and it seems that it is saved as `.opus`, not `.webm`. Navidrome should pick this up without the need for any conversion.

**Comment by deluan** [comment]
Ah, you mean like, a sidecar file. I'm not sure if I want to support these non standard files. [Someone is working](https://discord.com/channels/671335427726114836/704303730660737113/1068564291755708538) on reading the format used by this foobar plugin: https://www.foobar2000.org/components/view/foo_external_tags). If they ever complete and contribute it back, then maybe :)

Closing this now because, as mentioned by @certuna , it is an upstream (taglib) limitation. Please let me know if you have any other concerns.
