### ISSUE TITLE
Add support for retro music files (SNES SPC, PSX PSF, etc...)

### ISSUE THREAD

**Issue by panreyes** [navidrome/navidrome#1929]
I am a huge fan of classical OSTs, and I love their small sizes: just a few MBs will include complete OSTs.

Is there any way to play SNES SPCs or PSX PSFs with Navidrome? That would be my final reason to ditch my old Winamp :)

**Comment by vs49688** [comment]
I'd imagine the main issue here would be tagging, as most of these old formats don't store them, or at least not in an easily-accessible fashion. Where would Navidrome get the tags from?

**Comment by panreyes** [comment]
That would be not problem, dumped SPCs use to include at least the name of the game (which could be interpreted as the album) and the name of the song at least, and sometimes also the composer.

There is a library that could be a good middleware for playing SNES SPCs:
https://github.com/dgrfactory/spcplay

**Comment by vs49688** [comment]
Provided FFmpeg can play them, I don't see any reason why they wouldn't work already (but you'd have to switch to the FFmpeg scanner). Otherwise, https://github.com/taglib/taglib would need to be updated to support them.

If FFmpeg can't play them, then you're SoL anyway.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
The best method for such formats, especially to preserve them for the future, is to convert them to MP3, FLAC. I've done the same for some really old formats (like HSC as an example) that don't even play on the latest operating systems anymore because they only run in 16-bit environments with native hardware. Because some really old formats only play correctly under DOS and can't be converted digitally, and need to be recorded via analog out->analog in connection.

Another preservation issue also is, that even if they can be emulated they often don't sound like the original played on their native environments. That's why I still have old machines with as an example XP and SB AWE 32 + Waveblaster daughter boards to accurately play and record them into MP3, FLAC to preserve them. I even still have a C64 and an Amiga for that purpose, because SID as example still sounds best on C64 and some MOD Formats only play accurately on Amiga.

**Comment by panreyes** [comment]
> Provided FFmpeg can play them, I don't see any reason why they wouldn't work already (but you'd have to switch to the FFmpeg scanner). Otherwise, https://github.com/taglib/taglib would need to be updated to support them.
> 
> If FFmpeg can't play them, then you're SoL anyway.

Yes, you are right! I did not know that FFmpeg can directly play them, but it can thanks to the library Game Music Emu: 
```
@section Game Music Emu

FFmpeg can make use of the Game Music Emu library to read audio from supported video game
music file formats. Pass @code{--enable-libgme} to configure to
enable it. See @url{https://bitbucket.org/mpyne/game-music-emu/overview}.
```!
But, taglib does not support reading those formats yet. Thank you for your ideas though!

**Comment by panreyes** [comment]
> The best method for such formats, especially to preserve them for the future, is to convert them to MP3, FLAC. I've done the same for some really old formats (like HSC as an example) that don't even play on the latest operating systems anymore because they only run in 16-bit environments with native hardware. Because some really old formats only play correctly under DOS and can't be converted digitally, and need to be recorded via analog out->analog in connection.
> 
> Another preservation issue also is, that even if they can be emulated they often don't sound like the original played on their native environments. That's why I still have old machines with as an example XP and SB AWE 32 + Waveblaster daughter boards to accurately play and record them into MP3, FLAC to preserve them. I even still have a C64 and an Amiga for that purpose, because SID as example still sounds best on C64 and some MOD Formats only play accurately on Amiga.

Yes, of course I know that is an option, but emulated game music sound more than good enough for me, and its size is really small compared to having them converted to any wave format instead of having them interpreted. We are talking about dozens of collections in just 300mb instead of 20GB.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
> Yes, of course I know that is an option, but emulated game music sound more than good enough for me, and its size is really small compared to having them converted to any wave format instead of having them interpreted. We are talking about dozens of collections in just 300mb instead of 20GB.

Ohh yes size differences are huge of course, this is also so because some formats are only like notes and the sound is either generated via FM (SID, HSC,..) or via embedded samples (MIDI, MOD, SNES, PSX,..) and some also even use a combination of both. Now the issue with FM is that it only 100% sounds like the original if played on the same chip and the issue with the samples is that it only 100% sounds like the original when played on the same chip with the same sample bank.

For me the best player for old exotic formats is Deliplayer, it plays all Trackers, most of them natively and 230+ other formats and also supports all the various unpackers that were used, which is also important because some of those were packed or protected. And the best is, if it can play it, it also supports digital conversion and saving to mp3 etc.

All in all I already collected over 1GB of such "exotic" formats, and if you're interested I can give you access to the whole pack.
