### ISSUE TITLE
Add support for 2FA /OTP to improve security of publicly facing instances 

### ISSUE THREAD

**Issue by kowalcj0** [navidrome/navidrome#1942]
### Is your feature request related to a problem? Please describe.

In order to improve security of publicly facing instances it'd be great to have an option to enable 2FA (two-factor authentication) for all accounts.

### Describe the solution you'd like

Adding support for 2FA / OTP would improve security of publicly facing instances.
This should greatly reduce the number of brute force login attempts.

### Describe alternative solutions that would also satisfy this problem

Alternative or rather additional security measures include:
- captcha (e.g. [hcaptcha](https://www.hcaptcha.com), [MTCaptcha](https://www.mtcaptcha.com); etc)
- log-in rate limiting (e.g. 2 per minute, then 10 minute ban)
- support for hardware 2FA tokens

### Additional context

N/A

**Comment by K4r0qtuYNE5G4qgZ** [comment]
- There is already log-in rate limiting.
- Captchas are only for bots and against humans, they don't increase security,
- The only acceptable 2FA (two-factor authentication) in 2022 is FIDO U2F / FIDO2 webauthn

But since Navidrome does not support new registrations of users anyway, but only those who the admin added can log in, I don't see why.  As long as there are no security holes in Navidrome that allow the whole login system to be bypassed or direct access to the system behind it, i'm happy.

But should Navidrome then allow new registrations by users, then such measures might make sense.

**Comment by kowalcj0** [comment]
It looks like I missed this issue https://github.com/navidrome/navidrome/issues/242 before posting mine.
Indeed, auth requests are [rate limited by IP address](https://github.com/navidrome/navidrome/blob/v0.48.0/server/server.go#L81-L86). The default limit is [5 requests per 20 seconds](https://github.com/navidrome/navidrome/blob/v0.48.0/conf/configuration.go#L246-L247).
Once the threshold is reached, the `/login` endpoint will respond with [429 too many requests](https://github.com/go-chi/httprate/blob/v0.7.0/limiter.go#L47-L51)

re.
> The only acceptable 2FA (two-factor authentication) in 2022 is FIDO U2F / FIDO2 webauthn

It's definitely one of the options, but saying it's the only acceptable 2FA option is a bit of a stretch.
Regular software based [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password) are pretty good deterrent to brute-force login attempts.


As a side node, this comment on storing passwords https://github.com/navidrome/navidrome/issues/202#issuecomment-863589063 is interesting.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
> It's definitely one of the options, but saying it's the only acceptable 2FA option is a bit of a stretch. Regular software based [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password) are pretty good deterrent to brute-force login attempts.
> 
> As a side node, this comment on storing passwords [#202 (comment)](https://github.com/navidrome/navidrome/issues/202#issuecomment-863589063) is interesting.

It might be a bit of a stretch, but for me it is so because all these TOTP and HOTP things are just annoying and insecure.
Because unlike FIDO, the secrets are shared and stored on the server and then you also have to install additional software to generate them where they are stored again. And then you have to copy the generated codes out and paste them in etc. No phishing protection at all, everything a bit Stone Age.

And about  the side note, you can set a Passphrase to encrypt them:
`PasswordEncryptionKey*	ND_PASSWORDENCRYPTIONKEY	Passphrase used to encrypt passwords in the DB.`
Which is strongly recommended because else it uses a "Predefined Passphrase".

No idea why the author prefers this rather complicated method instead of simply hashing them with a salt that could be defined in config or e.g. to encrypt them with themself and thus make it irreversible.

With such security questions, I always consider that the server itself could be hacked. And from that point of view, neither the current method of storing the passwords nor TOTP/HOTP would be secure. Because a potential attacker also gets all the shared 2FA secrets and can also recover the passwords in plain text. In comparison, with FIDO and hashed/self-encrypted passwords, such an attacker would only get useless garbage.

**Comment by kowalcj0** [comment]
Hi @deluan 
I really like the looks of Authelia, especially because it can be easily integrated with so many reverse proxies. 
How would it work with all sorts of mobile clients? e.g Ultrasonic, DSub, Audinaut or Subtracks?
Thanks

**Comment by deluan** [comment]
> Hi @deluan I really like the looks of Authelia, especially because it can be easily integrated with so many reverse proxies. How would it work with all sorts of mobile clients? e.g Ultrasonic, DSub, Audinaut or Subtracks? Thanks

Unfortunately [reverse proxy authentication](https://www.navidrome.org/docs/usage/security/#reverse-proxy-authentication) can only work with the Web UI. The Subsonic API protocol does not allow any kind of security "enhancement" (2FA/OTP, Hashed passwords, LDAP integration, etc...). You'd need to have passwords set in Navidrome for the users who want to use any Subsonic client.

**Comment by kowalcj0** [comment]
Thanks @deluan for the explanation and a handy link.
Looks like Subsonic Dev would have to add support for 2FA/OTP etc first, before clients could offer it to clients.
Since Subsonic it's basically an abandonware, this will probably never happen.
Thanks all for your comments.
