### ISSUE TITLE
Embedded art being used for entire album

### ISSUE THREAD

**Issue by c0utta** [navidrome/navidrome#1969]
### Description

Using the following setting in navidrome.toml:
CoverArtPriority="embedded, cover.*"

One media file in an album has an imbedded image, but Navidrome uses the embedded image for all media in that album.  This is troublesome for compilations where different imbedded images may be used.  For example, I use an imbedded artist image in compilations, or may even use the album image (if I don't have the album)

### Expected Behaviour

Expected that only the media file with the imbedded image would display that image

### Steps to reproduce

1. Insert CoverArtPriority in navidrome.toml 
2. Restart Navidrome
3. Add imbedded image to a single media file in a compilation 
4. Play another media file in the compilation
5. The "spinning" image displayed is of the imbedded image (instead of blank)

### Platform information

 - Navidrome version: 0.48.0 (af5c2b5a)
 - Browser and version: Edge Version 106.0.1370.52 (Official build) (64-bit)
 - Operating System: Debian GNU/Linux 11 (bullseye)

### Additional information

Any other information that may be relevant or give context to the problem.

 - Can provide screenshots if required
 - Client used? Web

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I also noticed that if eg. I have an Album with four Discs and there is a different embedded image per Disc along with different Disc Title (Albums to have different Disc Titles and different Embedded Images per Disc isn't so uncommon) then only the Image of the first is displayed on top of the page and it doesn't change if switching Discs.

I also noticed that the spinning Image does change on per file basis if you have eg. 300 Files with each an different embedded Image, so the image is loaded, but only used for spinning disc animation not on Header (perhaps because this would need a refresh?).

But I find it much worse that the Disc Title is ignored, because there is so much empty space after the Disc Icon in the List to display it, so why isn't it shown?

If the Disc Title would be shown along with the Image on Header being changed if there are different embedded ones, that would open some really nice sorting options like one Album with 20 Discs instead of 20 Albums for Collections that mainly consists of Variations like Game Sound Collections where there are 20 Albums of the same recordings on 20 different Systems (Adlib, GM, C64, Amiga, Tandy, PC, Gameboy, Sega, NES, SNES, N64,...).

But yet changing the Header Image would only makes sense if the Header doesn't move out of screen if scrolling the List of Songs below, else you won't see it anyway if not always scrolling back on top to bring the Header back on screen.

**Comment by deluan** [comment]
This should only happens if you have `DevFastAccessCoverArt` set to `true` (default is `false`). 

You can confirm the behaviour in the [Demo](demo.navidrom.org) site. Look for the [8-bit lagerfeuer](https://demo.navidrome.org/app/#/artist/91c3901ac465b9efc439e4be4270c2b6/show) album, by 
_pornophonique_. Let me know if that's what you expect.

**Comment by c0utta** [comment]
@deluan: I don't have that setting - here is my config file:

MusicFolder="/mnt"
DevActivityPanel=false
EnableStarRating=false
SessionTimeout="72h"
CoverArtPriority="embedded, cover.*"

**Comment by deluan** [comment]
@c0utta if you don't have that flag set your installation should behave the same as the demo site. If it is not working, try clearing the cache (`DataFolder`/cache), and restarting Navidrome

**Comment by c0utta** [comment]
@deluan - I have worked out the issue and it is repeatable.

Imbed album art into a single file where no cover.* exists.

Wait for Navidrome to process the change - every file for that album will now use the imbedded art.

Add cover.* to the folder, but Navidrome does not change the other non-imbedded files to use cover.*

Your demo site works perfectly for that example, but I suspect the album art was added first, before the imbedded track art.

**Comment by deluan** [comment]
@c0utta The cover art resolution was refactored in latest versions. Can you confirm this is still an issue? You may have to clear the cache of both Navidrome and the browser/client to see it working.

@K4r0qtuYNE5G4qgZ:

> I also noticed that the spinning Image does change on per file basis if you have eg. 300 Files with each an different embedded Image, so the image is loaded, but only used for spinning disc animation not on Header

Yes, it is currently only used in the player, not elsewhere

> But I find it much worse that the Disc Title is ignored, because there is so much empty space after the Disc Icon in the List to display it, so why isn't it shown?

What do you mean? I can see disc titles, this was implemented a long time ago:
<img width="1316" alt="Screenshot 2023-02-17 at 8 27 59 PM" src="https://user-images.githubusercontent.com/331353/219824349-7a761730-ade6-4fbc-926c-5354b8b92c1e.png">

**Comment by K4r0qtuYNE5G4qgZ** [comment]
> @K4r0qtuYNE5G4qgZ:
> > But I find it much worse that the Disc Title is ignored, because there is so much empty space after the Disc Icon in the List to display it, so why isn't it shown?
> 
> What do you mean? I can see disc titles, this was implemented a long time ago

Was an Tag Issue that I meanwhile fixed

The Issue is `DISC TITLE` is ignored and only `SETSUBTITLE` is used on MP3 and on M4A only `DISCSUBTITLE` is used and `SETSUBTITLE` is ignored etc.

And for some reason some MP3 also had `DISC TITLE` which apparently is wrong, duno which tagger wrote them.
