### ISSUE TITLE
Transcode only 1 file type?

### ISSUE THREAD

**Issue by soup-eater** [navidrome/navidrome#2033]
### Describe the solution you'd like

I would like to transcode only flac files and direct stream other file types.

### Describe alternative solutions that would also satisfy this problem

Is there a way i can set the ffmpeg commands to do this?

**Comment by soup-eater** [comment]
is there a way can add a [batch process](https://stackoverflow.com/a/33766147/12999343) instead of just the ffmpeg command?

**Comment by metalheim** [comment]
> 

What 

> is there a way can add a [batch process](https://stackoverflow.com/a/33766147/12999343) instead of just the ffmpeg command?

What are you trying to achieve? The transcoding options refer to 1 specific file that is currently beeing played. Theoretically, you could write anything in a custom transcoding config https://www.navidrome.org/docs/usage/configuration-options/#available-options
Though not advised

**Comment by soup-eater** [comment]
Yes I was thinking of editing the Transcoding config as an "if" statement. If flac -> transcode, else -> direct stream.
Sorry if i wasnt very clear

**Comment by edenist** [comment]
As a quick workaround, with the downsampling patch I would recommend setting the max bitrate to 320. 100% of my non-flac files are below this bitrate so this would effectively only trigger transcoding on flac.

**Comment by deluan** [comment]
@soup-eater , there are currently two workarounds for this:

1. Use the downsampling option as @edenist suggested. This will be available in the next release coming soon, if you don't want to work with the unstable `develop` build
2. If you have scripting skills, you could write a script to be used instead of `ffmpeg` in the transcode command. It could check for the extension and only call `ffmpeg` if the extension is `flac`. If not, just `cat` the file.

Anyway, I'm closing this as it's a use case that will be handled in #351 . Please subscribe to that issue if you want to be notified of its progress.
