### ISSUE TITLE
Symlinks doesn't seem to be scanned

### ISSUE THREAD

**Issue by 123321mario** [navidrome/navidrome#2114]
### Description

My setup is like this:

Navidrome root directory: C:\music
Contents of C:\music:
C:\music\european (symlink to \\server\disk1\music\european)
C:\music\japanese (symlink to \\server\disk2\music\japanese)
C:\music\random_album\random_song.mp3 (real file on disk)

Only the random_album is showing on Navidrome

I was using Navidrome with symlinks on my old server and it worked fine.
Both servers are running the same Windows 11 install (just different specs)
Now that I reinstalled exactly the same way on the new server, the symlinks doesn't seem to be scanned by Navidrome.
As seen in issues #193 and #396 the symlinks should be supported.

### Expected Behaviour

Navidrome should scan the linked directories.

### Steps to reproduce

1. Install Navidrome
2. Setup root path to a folder containing symlinks
3. Start Navidrome and see 

### Platform information

 - Navidrome version: 0.48.0
 - Browser and version: Microsoft Edge 109.0.1518.61
 - Operating System: Windows 11, installed with shawl

### Additional information

Logs says `msg=\"Invalid symlink\" dir=\"C:\\\\music\\\\european\" error=\"CreateFile C:\\\\music\\\\european: Le serveur spécifié ne peut pas exécuter l’opération demandée.\" `

From french to english : `The specified server cannot perform the requested operation`

Symlink is working fine with windows explorer and other apps

**Comment by Teflon98** [comment]
I have two /mnt's that are SMB shares to local machines.
Created symlinks to them inside a /music folder.
In /music, able to navigate in and out of them.

Navidrome errors when launching:

`time="" level=error msg="Invalid symlink" dir=/music/folder1 error="stat /music/folder1: no such file or directory"
time="" level=error msg="Invalid symlink" dir=/music/folder2 error="stat /music/folder2: no such file or directory"`

Using Docker on Ubuntu

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hmm two separate issues here.

1. Symlinks only work on files/directories on the same machine, you can't symlink a network share like that.
2. Why symlink a mount if you simply can mount it where you need it?

Another thing to check is if widelinks are enabled (only linux) setting doesn't even exist on windows.

And in general, first mount the share permanently, then create the symlink to it, but only 100% works in linux, on windows there may be some other issues with NTFS symlinks not working with SMB-Shares etc.

And last but not least, there can also be permission issues, because the symlink doesn't necessarily share the permissions of the SMB-Share.

**Comment by kostas-theo** [comment]
Just in case the OP or anyone else has run into the same issue I did - check to see where your symlinks actually point. In my case I have two directories `/music/original` and `/music/new` with the "new" directory full of symlinks to the "original". However because my symlinks were generated by a program running in a container, all links point to a different directory `/orig` which doesn't exist inside my Navidrome container. My quick fix was to re-mount `/music/original` to `/orig` which fixed my symlinks. :)
