### ISSUE TITLE
Downloading a multi-CD album puts all songs in single directory

### ISSUE THREAD

**Issue by ttrei** [navidrome/navidrome#2121]
### Description

When you download an album with multiple CDs and unzip the downloaded file, all songs are in the same directory, not grouped by CDs.

### Expected Behaviour

One directory per CD.

### Steps to reproduce

1. Open a multi-CD album in Navidrome
2. Click on DOWNLOAD
3. Unzip the downloaded file

### Platform information

 - Navidrome version: 0.48.0 (af5c2b5a)
 - Browser and version: Firefox 109.0
 - Operating System: Debian bookworm, binary Navidrome release

**Comment by K4r0qtuYNE5G4qgZ** [comment]
That's why i rename my multi-CD Albums to:
1-01, 1-02, 1-03,..
2-01, 2-02, 2-03,..
...
So that even if all are moved out of the CD1, CD2,.. folders they are sorted correctly.

And yeah Navidrome perhaps also should keep the folder structure of the album. But I guess there could be the same issue as with the request for using folder structure to sort albums eg. where does the Album start and end.

Examples:

X:\Music Library\Album1\CD1
X:\Music Library\Album1\CD2
X:\Music Library\Album1\CD3
X:\Music Library\Album2\CD 1
X:\Music Library\Album2\CD 2
X:\Music Library\Album3\
X:\Music Library\Album4\Disc1
X:\Music Library\Album4\Disc2
X:\Music Library\Album5\Album5 Disc 1
X:\Music Library\Album5\Album5 Disc 2
X:\Music Library\Artist1\Album6\CD1
X:\Music Library\Artist1\Album6\CD2
X:\Music Library\Album7\
X:\Music Library\Album7\Bonus
X:\Music Library\Album8\
X:\Music Library\Album8\CD1
X:\Music Library\Album8\CD2
X:\Music Library\Album8\Bonus\Part 1
X:\Music Library\Album8\Bonus\Part 2

Probably not so straightforward to determine which folder exactly now should be zipped that contains the whole structure for that specific album. 

Another possibility would be that Navidrome simply recreates a standardized structure from tags for the zips, like if the album has Discnumbers\setsubtitles etc. It simply create folders for them, copy the corresponding files into it and then zip that structure. But to do this, the files would have to be copied around first, which is also more tedious as simply zipping all files into one archive like it does now.

**Comment by deluan** [comment]
> That's why i rename my multi-CD Albums to:
> 1-01, 1-02, 1-03,..
> 2-01, 2-02, 2-03,..

@K4r0qtuYNE5G4qgZ : This is also what I do. Actually, this is what `beets` does for me ;)

Zips are created on the fly, not staging files first. Currently Navidrome uses a mix of tags and the filename to name the files inside the zip. I can add the DiskNumber to the file's path, if the album has multiple discs.
