### ISSUE TITLE
Genre(s) from Last FM

### ISSUE THREAD

**Issue by alanman87** [navidrome/navidrome#2166]
### Is your feature request related to a problem? Please describe.

Most of my music is missing a genre tag. Editing Genre tags is difficult on headless linux for the novice user like me. I could do it on windows but also that's a monumental task given my existing library size.

### Describe the solution you'd like

I would like Navidrome to pull genres from Last FM if possible at an album level. This appears to be supported for most if not all albums on Last FM. It doesn't need to save those to the files as I understand Navidrome should be read only for the library.

If it could pull multiple, such as the top 3 or 5 tags would be amazing. ~~But I understand multi-genre tags are not supported yet. In that case could multiple genres per album be added when it is supported?~~

### Describe alternative solutions that would also satisfy this problem

I'm not sure what would help aside from manual editing which still is tedious for those with existing libraries.
Edit: I would not like to use an automated tagging tool as there is potential to change existing tags for some multiple edition albums I have in my library.

### Additional context

![image](https://user-images.githubusercontent.com/28031959/218286447-50de107c-9151-4639-bfb9-b155e7f8724b.png)

**Comment by deluan** [comment]
Thanks for the suggestion, but just to be clear: Navidrome DOES support multiple-genres, as you can see from the demo server:
<img width="1523" alt="Screenshot 2023-02-11 at 7 38 58 PM" src="https://user-images.githubusercontent.com/331353/218287093-61da3cab-599c-49e8-8f93-1e303c1c6203.png">

**Comment by dweymouth** [comment]
It's Subsonic clients that don't support multiple genres (because the underlying API doesn't support it) but even then there is partial support for multi genres, because the albums will appear under each genre they're tagged with when searching by genres in a Subsonic client

**Comment by dweymouth** [comment]
@alanman87 in the meantime you might want to look into an automated tagging tool like Beets or MP3Tag - they may be able to get your genre tags sorted out

**Comment by alanman87** [comment]
Thanks for clarifying that fact, @deluan 

I appreciate the suggestion @dweymouth. My library tags are otherwise perfect and I fear what an automated tool may do.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Oh yeah, genre tags also are or were my problem child...
Especially after I noticed that Musicbrainz has no Genre tags and I had to re-tag all those I already did with Discogs again to get them. Another issue it only sets some Genres and the others in Styles, so I had to code a little scripts that transfers all from Styles into Genres.

@alanman87 In Mp3Tag you can so it so that really only the Genres/Styles tags are got(only discoqs) and are written to file, but it's stil a lot of work, because you need to do it per Album, no batch processing possible with that specific issue.

And Navidrome also has some weird behaviour, it sorts them like it wants and not like they are in the tags.
Example:
InFile: Classic, Baroque
Navidrome: Classical, Baroque or Baroque, Classical, the order changes from album to album, despite being everytime the same order inFile.

But well, i'm soon finished with re-tagging now, some more weeks and I should be done.

**Comment by alanman87** [comment]
Mp3Tag does not have a command line Linux version, or any Linux version for that matter. My own internet speed is a bit slow so my Navidrome server is headless and remote. It's a bit of a chore to download, tag, then re-upload and would take quite a while.

@K4r0qtuYNE5G4qgZ I have noticed the same behavior on my end. The few existing albums I have with multiple genre tags are displayed in random order.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
My Navidrome server is headless too, but I host it myself locally and so I have a samba share to the library for such tasks.
Perhaps there is some command line tagger for Linux that also can retrieve genres from Discogs else it's a bit annoying for you with that setup.

And yeah it's a bit weird that the Genres are displayed in random order, I would expect them to be displayed in the order they are set in the tags.

**Comment by alanman87** [comment]
I would still like to see this suggestion happen. Please remove the stale tag.
