### ISSUE TITLE
Cache artwork thumbnail

### ISSUE THREAD

**Issue by mayli** [navidrome/navidrome#2200]
### Is your feature request related to a problem? Please describe.

Just found out that navidrome will cache the original copy instead of thumbnail of the artwork,
I got a 16.8 MiB jpeg file there and it seems to be a waste of cache usage.

cache/images/5a/09$ file 5a098fcc61261ca71a3cd410190ad0c4eb80059c
5a098fcc61261ca71a3cd410190ad0c4eb80059c: JPEG image data, Exif Standard: [TIFF image data, big-endian, direntries=13, height=3454, bps=0, PhotometricIntepretation=RGB, orientation=upper-left, width=3906], baseline, precision 8, 3419x2975, components 3

### Describe the solution you'd like

Thumbnail the artwork to a reasonable size such as 226x226 jpeg (YouTube Music), which could take only 6291 bytes per artwork.

### Describe alternative solutions that would also satisfy this problem

Webp is also fine.

**Comment by deluan** [comment]
This is intentional.

Original covers are stored in cache because it can be expensive to obtain them in at least two situations:
1) The image is embedded and can only be extracted with `ffmpeg`. This means we have to execute `ffmpeg` to get the image
2) The image is from an external site (Last.fm). To get the original we would need to fetch it again.

And we need the original for when the client requests a resize. I don't want to resize a resized image, and lose some quality in the process.

Also, even if the image is a `cover.jpg` external file, it could be stored in a slow network device. This is my case, which motivated me to implement this way.

Anyway, storing the full image is not a real big problem: Most clients only asks for the image if it is item has changed. If the original in the cache is not accessed, it will be delete to make room for other images.

**Comment by mayli** [comment]
I have some quite large cover.jpg around, they just keep pushing out lots of artworks, which causes performance issue since we may need to access the slow network device. The only downside is the quality loss for artwork or double resize, and I could live with that as long as the thumbnail could be loaded in a snappy way. I prefer a lossy version rather a slow version on those images.

**Comment by mayli** [comment]
@deluan It seems we are storing the thumbnail of artwork, 

https://github.com/navidrome/navidrome/blob/5fc4076aec631ed5e2ff0b19bf5fe4f4c3bac170/core/artwork/cache_warmer.go#L132

Just somehow it didn't work for this file.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
> And we need the original for when the client requests a resize. I don't want to resize a resized image, and lose some quality in the process.

👍 Thanks.

**Comment by deluan** [comment]
> they just keep pushing out lots of artworks, which causes performance issue since we may need to access the slow network device

Who is "they" in this context? Clients? Which client do you use? It should not request the image every time it needs to show it, although that's what I think Substreamer does. 

But then you seem to be complaining about a different issue: You want clients to receive a resized image when they request the original. That's on them to request the size they really need, instead of the original, and they should only re-request the image if the URL changes. 

If you want the clients to receive resized images when they request originals, it's up to you to change the originals in your library. Assuming you have external .jpg files, you could keep the originals with their current name, resize them with some external tool, and save it with a name like "thumbnail.jpg", Then you can change the `CoverArtPriority` to add "thumbnail.jpg" in front of the other options, so Navidrome would use it as "original".

> Just somehow it didn't work for this file.

This pre-populates the cache with the original and a reduced 300x300 version of it, to be used by the UI (and other clients that use this size, like DSub)

**Comment by mayli** [comment]
The scanner/cache_warmer. So we store both the original and the resized copy in the cache, I think that explains the behavior in my collection.
I wish there is an option to 
 1. skip storing the original
 2. perform a resize from the thumbnail for users who doesn't want to pre-thumbnail their artworks.

```
2137444 ./e7/41/e741b87f041fe21ed0af307de7d4aa06bf64d334
2394281 ./64/e0/64e0dd3e4a495d4950e4723a1dece9f585642837
2444550 ./6c/12/6c12de8dab23074744198179ff3a336dbe9c9453
2773241 ./fb/79/fb79064d2695b96686752c3d366fc971f7b15489
4848661 ./cc/b3/ccb3a962a5db4e793f02b11c963b8677c7b20a5a
```

Otherwise for every new album with a big cover.jpg (usually from a scanner),  if I forget to pre-thumbnail the artwork, the cache_warmer will purge tons of items. Which kind of rendering the cache less useful and annoying slow on access.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Here my Structure I follow:
```
_
 |_Artist - Album
                 |_Art (Contains the Big ones 10-100MB partially up to 18'000px PNGs, JPGs)
                 |_(CD1, CD2,..) [If multi Disc or if it has Discnames]
                 |             |_Media Files with embeded (600px - 1200px, Square JPG)
                 |[else/or]
                 |_Media Files with embeded (600px - 1200px, Square JPG)
                 |
                 |_folder.jpg (600px - 1200px Square JPG)
                 |_(possible other unused small cover, front etc. JPGs that are present already)
```
For every Album I take the best possible quality cover i can get and then clean, optimize, resize it to a 600-1200px (depends on source size) Square (with black borders if needed to preserve proportions) and save it as a JPG which then is the folder.jpg and is also embedded in all files belonging to that Album.

As it can be imagined especially processing all covers takes time, much time, I almost spent 6 Months already re-tagging.

Most just don't care that the covers are clean, 99% have dirty edges, wrong gamma, specks of dust, aren't square etc. I hate that... I want mine clean, yes perfect. And I guess I have to suffer for this perfection, but I always say if a thing is worth doing, it's worth doing well. 🙂

**Comment by mayli** [comment]
Maybe I used too much of plex, where the idea is keep index (meta, artworks) in the plex external database, andhaving the origin untouched (read-only access the nfs share).

**Comment by deluan** [comment]
> Maybe I used too much of plex, where the idea is keep index (meta, artworks) in the plex external database, andhaving the origin untouched (read-only access the nfs share).

That's how it should be, and I strive to make Navidrome works this way, but comparing one guy working on his open source hobby project with a company that makes money from a closed source product and have the cash to pay for a team of dedicated devs, it is not really a fair comparison ;)

Sometimes I even discard ideas and features, even working PRs, because of the added code and complexity that *I* will have to maintain and give support.

Anyway, I think grooming your library makes it future-proof and easier to move to other platforms if you ever want to. Even adding support for external cover files was something that I didn't want to do in the first place, as IMO embedding images are the proper way to have cover arts in your library.

**Comment by mayli** [comment]
I could work on this if anyone find this could be useful, like trading artwork quality for better cache hit ratio. 100MB could contain way more thumbnails if sacrifice the image quality a bit.

**Comment by dweymouth** [comment]
> IMO embedding images are the proper way to have cover arts in your library

Funny how opinionated we all are about music library management. IMO a folder.jpg or cover.jpg per albumis the way to go and I hate embedded art because it bloats file size :)

**Comment by dweymouth** [comment]
Also @deluan 
> Most clients only asks for the image if it is item has changed

Is there a way with Subsonic to know if the cover itself has changed? I don't think so. My client invalidates a cover in its cache after 24h in case the image itself changed on the server

**Comment by deluan** [comment]
> I could work on this if anyone find this could be useful, like trading artwork quality for better cache hit ratio. 100MB could contain way more thumbnails if sacrifice the image quality a bit.
> 
> ```
> ArtworkThumbnail=true/false
> ThumbnailHeight=300
> 
> on cache_warming
> if ArtworkThumbnail:
>   cache the artwork thumbnail at size=ThumbnailHeight
> on serving
> if ArtworkThumbnail:
>   if size<ThumbnailHeight:
>     resize the thumbnail again
>   return the cached   thumbnail 
> ```

Definitely not that easy, there's lots of cache invalidation logic in the `artwork` package, and when you request a resized image, it queries the original from itself, recursively, caching it in the process.

**Comment by deluan** [comment]
> Also @deluan
> 
> > Most clients only asks for the image if it is item has changed
> 
> Is there a way with Subsonic to know if the cover itself has changed? I don't think so. My client invalidates a cover in its cache after 24h in case the image itself changed on the server (sometimes I find better quality art and replace the covers)
> 
> Edit: I realized the cover art ID itself could change. Does navidrome assign a new cover art ID every time there's a change in the cover image? Even if so, that seems like something I couldn't rely on other servers necessarily doing.

Yeah, Navidrome changes the `coverArtId` when the art changes.

>  Edit2: the above only works for playlists. I don't think it's possible for a Subsonic client to know if album art changed without re-requesting it.

If album had the `changed` attribute (something we should add as par of the extensions) then the client could re-request the cover art for changed albums.
