### ISSUE TITLE
Cover Art embedded in m4a media file using FFMPEG is not used by navidrome

### ISSUE THREAD

**Issue by jkumeboshi** [navidrome/navidrome#2213]
### Description

I'm trying to use ffmpeg to process audio files to add metadata and embedded cover art.
For metadata such as title and artist I'm not having problems.
But I'm having troubles embedding a cover art that would be recognized by navidrome.

I tried follow command to add a cover art stream, that encode the cover art using default ffmpeg codec:
`ffmpeg -i 1.m4a -i 1.jpg -map 0:0 -map 1 -acodec aac  2.m4a`

I also tried follow command using mpeg4 as artwork codec:
`ffmpeg -i 1.m4a -i 1.jpg -map 0:0 -map 1 -acodec aac -vcodec mpeg4  2.m4a`

and both are recognized by many players, but not by Navidrome.

### Expected Behaviour

I would expect that Navidrome is able to extract cover art from media using all standard codecs.

### Platform information

 - Navidrome version: 0.49.3
 - Browser and version: Firefox 110
 - Operating System: Windows 11

### Additional information

this is the log when navidrome fails to get the artwork:

```
time="2023-02-27T09:29:28Z" level=trace msg="Looking for album art" id=al-cfe210816089f5edf3edf1a117e01ae6 requestId=4bf318694e2b/FKSYlJ2pD7-000038
time="2023-02-27T09:29:28Z" level=warning msg="Error extracting image" error="empty path given for artwork" path= requestId=4bf318694e2b/FKSYlJ2pD7-000038 size=300
time="2023-02-27T09:29:28Z" level=debug msg="HTTP: GET http://music.fedibox.com/rest/getCoverArt?u=b&t=[REDACTED]&s=[REDACTED]&f=json&v=1.8.0&c=NavidromeUI&id=6a61f92570c24e11d662b7b0609baf93&_=2023-02-27T09%3A27%3A25.209647484Z&size=300" elapsedTime=144.5ms httpStatus=200 remoteAddr=192.168.178.45 requestId=4bf318694e2b/FKSYlJ2pD7-000038 responseSize=85011 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
```

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hmm dunno about ffmpeg but the covers embedded by Mp3Tag are used by Navidrome v0.48.0

![image](https://user-images.githubusercontent.com/5566460/221670454-c56e34f2-54b7-4e76-8838-d991a56eacb8.png)

So either a new bug on Navidrome v0.49.3 or ffmpeg doesn't embed them correctly.

**Comment by jkumeboshi** [comment]
I was using 0.48 and just upgraded to 0.49.3 to see if something was changed, since there in the changelog the Artwork handler now should fallback to "ffmpeg extract" as last resort before using the blue disk as default image.

I handle my library with MEdiaMonkey GUI Application and it's able to add jpget cover files that are successfulyl seen by Navidrome. But I cannot find a command line tool to add a cover to m4a file, and I need it to automatically process files.
Do you know any command line tool to add the cover image to m4a files?
`lame -ti coverart.jpg in.m4a` says that the mp4 container is not supported (works fine with mp3 container, but I should reencode all file to mp3...).
eyeD3 is able to add an id3 tag with the image, but then the file is corrupt since in not anymore a valid m4a file container and is not played anymore. I think that as many id3 tags, it expects an mp3 container and just don't check it out adding the id3 header.

Anyway, ffmpeg is able to add cover art to m4a files and his output is recognized by many player, but not by navidrome.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
There are only a few i know of:

AtomicParsley:
https://atomicparsley.sourceforge.net/#:~:text=AtomicParsley%20is%20a%20lightweight%20command,m4p%2C%20.
```
sudo apt-get install atomicparsley

Then change to the directory containing the m4a files and run the following:

for i in *.m4a
do
AtomicParsley "$i" --artwork cover.jpg --overWrite 
done
```

TagEditor Project:
https://github.com/Martchus/tageditor
`tageditor -s cover=ju.jpg --max-padding 100000 -f ki.m4a`

And yes, ID3 tags on M4A or FLAC leads to issues, the same also for APEv2 tags on MP3, FLAC files.
If the Tagger is good, the Files shouldn't get corrupted, but it cause other issues like invisible tags or Navidrome not reading the covers and tags even if there etc.

It's also sometimes hard to clean them, With Mp3Tag I simply copy the tags, remove all tags and then paste them, they are then applied correctly, but if you can't use Mp3Tag it can be bothersome to clean such chimeras, because they are hard to spot.

**Comment by deluan** [comment]
Hey @jkumeboshi is this still an issue for you? If yes, try to follow these steps to troubleshoot what could be happening: https://github.com/navidrome/navidrome/issues/2190#issuecomment-1434018334

Please let me know if this helps.

**Comment by phw** [comment]
> Anyway, ffmpeg is able to add cover art to m4a files and his output is recognized by many player, but not by navidrome.

The difference between this usage of ffmpeg and the other tools (e.g. MP3Tag) is how the image is placed in the file. The usual approach for adding cover images for audio files is by adding them to the metadata inside the MP4 (as `covr` atom). This is definitely the most compatible way of handling this.

What your ffmpeg command is doing is that it makes use of MP4 being a container format and it adds a second video stream with that image. Check this ffprobe output of an otherwise empty MP4 audio file (I cut out the not relevant ffmpeg version info):

```
% ffprobe test.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.m4a':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2007-02-23T09:07:16.000000Z
    encoder         : FAAC 1.24
  Duration: 00:00:00.11, start: 0.023220, bitrate: 193 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 135 kb/s (default)
    Metadata:
      creation_time   : 2007-02-23T09:07:16.000000Z
      vendor_id       : [0][0][0][0]
```

Now after running `ffmpeg -i test.m4a -i test.jpg -map 0:0 -map 1 -acodec aac  test-with-cover.m4a` to add this image:

```
% ffprobe test-with-cover.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test-with-cover.m4a':
  Metadata:
    major_brand     : M4V 
    minor_version   : 512
    compatible_brands: M4V isomiso2avc1
    encoder         : Lavf59.27.100
  Duration: 00:00:00.09, start: 0.000000, bitrate: 536 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 106 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuvj444p(pc, bt470bg/unknown/unknown, progressive), 140x96 [SAR 1:1 DAR 35:24], 653 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

Essentially this now became a video file, with a h264 "video" just displaying the still image added. If you have your general purpose multimedia playback software that can handle video it will show this during playback. But if the software does not yet support video playback (as e.g. Navidrome) than extracting this image from the video (which involves decoding the h246 and read the first frame as an image) is much more work than just grabbing the ready-to-use JPEG from the metadata.

I hope this could give some background to the issue here.

**Comment by jkumeboshi** [comment]
Yes, this is correct, looks like that M4A covers are embedded as single still images in a stream video.
But navidrome is able to use this still image, at least if it's encoded using the `mjpeg` codec.
That's maybe because extracting a single JPEG frame from a MJPEG stream is much easier than decoding an h264 stream to get a frame?

Following track had cover added by Media Monkey and is being correctly displayed by Navidrome:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2008-03-09T12:23:17.000000Z
    title           : Addicted
    artist          : Amy Winehouse
    album           : Back To Black
    grouping        : Other
    track           : 11
    date            : 2006
    comment         : by dd4651
    compilation     : 0
    gapless_playback: 0
    encoder         : iTunes v7.6.0.29, QuickTime 7.4
    iTunSMPB        :  00000000 00000840 000002A8 00000000006F2118 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    iTunNORM        :  00001445 00001798 0000B866 0000BF01 00012751 00012751 00008000 00008000 00001676 00000DED
    composer        : Amy Winehouse
    album_artist    : Amy Winehouse
    genre           : Other
    disc            : 0
    ORGANIZATION    : Universal Distribution
    TRACKNUMBER     : 11
    replaygain_track_peak: 1
    replaygain_track_gain: -9,07999992370605
    replaygain_album_gain: -9,63000011444092
  Duration: 00:02:45.21, start: 0.047889, bitrate: 131 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2008-03-09T12:23:17.000000Z
      vendor_id       : [0][0][0][0]
    Side data:
      replaygain: track gain - -9.000000, track peak - 0.000023, album gain - -9.000000, album peak - unknown,
  Stream #0:1[0x0]: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)

```

**Comment by phw** [comment]
Indeed, there is explicit support for reading cover art from mjpeg stream: https://github.com/navidrome/navidrome/blob/759ff844e2d0b89661b6c5c83c5609d3f859bbc5/scanner/metadata/ffmpeg/ffmpeg.go#L82

So I guess this could be added similarly for h264 video. The immediate solution would be to add the pictures as mjpeg instead of h264 video. It's also kind of cleaner, as mjpeg essentially is a list of jpeg files (one in this case :)).
