### ISSUE TITLE
Navidrome can not support DFF and ISO  music file

### ISSUE THREAD

**Issue by agedcat** [navidrome/navidrome#2223]
After I copy DFF or ISO music file to the music file path, navidrome can not scan out. Sonixd cannot scan out ethier.

**Comment by metalheim** [comment]
.iso isnt really a music format file, but rather a disk Image (whole file System) container.

.dff files: there is a comment in #778 that it is not supported at the moment. Quick googling also tells me that dff doesnt support any tags, so it doesnt Sound like an ideal format for a streaming Application like navidrome. Maybe convert to dsf instead? Dsf should be scanned and metadata extracted

**Comment by agedcat** [comment]
.ISO can aslo be Lossless music format. .dff convert to .dsf is not a easy thing, some professional tools are essential. It is best way that .iso .dff can be played online.

**Comment by andrewgdunn** [comment]
@agedcat you really should extract these tracks to DSF, it is what library maintainers use because it's superior to DFF in that it can hold metadata.

Suggesting that navidrome should arbitrarily be able to extract on the fly from ISO is a _lot_ to ask when there exists a __golden pathway__ for everyone to maintain DSD content as DSF files.

This issue should be closed.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I simply converted all DSFs to FLAC, problem solved.

**Comment by agedcat** [comment]
@andrewgdunn @K4r0qtuYNE5G4qgZ I found  a tool sacd_extract that can easily convert .iso .dff to .dsf, problem solved.many thanks.
maybe navidrome can support to  convert .iso .dff to .dsf online using sacd_extract. it is just a immature idea.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@agedcat There is also an SACD2Flac GUI that uses Saracon, but extracting them to 24bit 96/88.2 DSF and then directly converting to 24bit 48/44.1 FLAC with Aimp is much faster and quality is the same. I tested the files with Spectrograms and 96/88.2 makes no sense, because 99.99% there are anyway no freqs above 23khz, and converting them to 48/44.1 saves about 50% filesize. And additionally while not all players can play DSF they all support FLAC.

**Comment by agedcat** [comment]
@K4r0qtuYNE5G4qgZ  flac is a more popular music format. there is no problem.
