### ISSUE TITLE
[Bug]: Naming convention is different across releases

### ISSUE THREAD

**Issue by tessharp** [navidrome/navidrome#2673]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1

### Current Behavior

The naming convention for the Windows x64 package changes across multiple releases, which makes automation scripts that rely on looking at the GitHub release index fail. For example, here are a number of naming differences in the past releases:

- 0.50.1: navidrome_0.50.1_windows_amd64.zip 
- 0.50.0: No Windows package
- 0.49.3: navidrome_0.49.3_Windows_x86_64.zip 

Furthermore, capitalization of names may cause issues for case sensitive file systems / scripts (i.e. "Linux" vs "linux")

### Expected Behavior

The suffixes to identify a specific platform should be consistent across multiple releases.

### Steps To Reproduce

1. Check a version release in GitHub
2. Get a specific platform naming convention (e.g. for Windows)
3. Check a different version release within GitHub
4. Get another naming convention for the same platform
5. The naming convention in both instances should match: (e.g. navidrome_#.#.#_windows_amd64.zip)

### Environment

```markdown
N/A - Issue not directly related from the use of Navidrome
```

### How Navidrome is installed?

Docker

### Configuration

```toml
N/A - Issue not directly related from the use of Navidrome
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Yes, I failed to mention this in the release notes, my bad. 

This is a result of a [deprecation in GoReleaser](https://goreleaser.com/deprecations/#archivesreplacements), and was changed [here](https://github.com/navidrome/navidrome/commit/f941347cf189387b0bca8c9cac7c747e343b5b10#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689). Instead of the "hack" proposed in the deprecation notice, I decided to go with the default Go binary naming convention.

The current naming convention will not change anymore, sorry for the trouble.
