### ISSUE TITLE
[Bug]: Navidrome doesn't daemonise properly (?)

### ISSUE THREAD

**Issue by vext01** [navidrome/navidrome#2689]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.50.1

### Current Behavior

Hi! I'm the maintainer of the OpenBSD package of navidrome.

I've been trying to track down why navidrome doesn't start at boot properly on OpenBSD. You can start it after boot via an rc script, just not during boot.

Looking at the logs during boot, I see:
```
time="2023-12-04T16:15:15Z" level=info msg="Received termination signal" signal=hangup
time="2023-12-04T16:15:15Z" level=info msg="Stopping HTTP server"
```

This comes one second after navidrome has come up!

After some digging and conversation with the OpenBSD folk, here's what I believe is happening:

 - OpenBSD's `rc(8)` starts navidrome during the boot process. Navidrome comes up with access to the console.
 - At some point `rc` revokes access to the console causing navidrome to receive a `SIGHUP`.
 - Navidrome catches the signal and terminates.

I *think* (and I'm no expert on this myself, so push back if I'm wrong), there are two things not right:
 - navidrome doesn't daemonise and start a new session via `daemon(3)`. This would prevent navidrome from receiving a `SIGHUP`.
 - semi-related: navidrome stops, instead of restarts, when receiving `SIGHUP`.

What do you think? Thanks

### Expected Behavior

 - Navidrome should daemonise using `daemon(3)`.
 - Navidrome should restart when receiving SIGHUP.

### Environment

```markdown
- OS: OpenBSD-current/amd64
```

### How Navidrome is installed?

Package

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by vext01** [comment]
Another note: to daemonise properly, navidrome would need to log to a file (e.g. via syslog(3)), because proper daemonisation requires that stdout and stderr are closed.

**Comment by deluan** [comment]
Thanks for maintaining the OpenBSD package. 

Let's discuss your two points:

### - SIGHUP

Even though it is common practice for daemons to restart/reload if this signal is received, it is not a strictly mandated behaviour. In the current implementation, it is not simple to introduce this behaviour. Currently, Navidrome [will terminate when receiving SIGHUP](https://github.com/navidrome/navidrome/blob/68ceeb9ea1b1b6750639d9156a0c9156e68b9f52/cmd/signaler_unix.go#L27). 

We could remove the SIGHUP from that handler, if it makes things easier for you.

### - Log to file/syslog/Windos logger/... 

> proper daemonisation requires that stdout and stderr are closed

I've never used OpenBSD, but I can create a initd/systemd/openrc unit in Linux and they can handle the logging for any app I want to setup as daemon.

Navidrome follows the [Twelve Factor App](https://12factor.net/) methodology as much as possible, including [logs](https://12factor.net/logs). The reason is to avoid bloating Navidrome's binary with libraries to route/store/rotate logs, specially because each supported environment has its own log tools that can better handle logs. 

As a maintainer of the package you probably create some script/unit to start/stop Navidrome, right? (I couldn't find the source code) Then you could redirect the output to a file or `syslogd`, right? Like it can be done with [OpenRC](https://github.com/navidrome/navidrome/blob/master/contrib/navidrome#L8) or [NSSM for Windows](https://www.navidrome.org/docs/installation/windows/#using-nssm) for example.

Let me know your thoughts.

**Comment by vext01** [comment]
Hi there! Thanks for the reply!

>We could remove the SIGHUP from that handler, if it makes things easier for you.

In the absence of a signal handler, a process will be killed when receiving `SIGHUP` so that wouldn't actually help.

You could have navidrome re-exec itself upon `SIGHUP`, but I assume there would be some cleanup it has to do first?

> Navidrome follows the [Twelve Factor App](https://12factor.net/) methodology as much as possible, including [logs](https://12factor.net/logs).

I've not heard of this, but it says:

> A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout. During local development, the developer will view this stream in the foreground of their terminal to observe the app’s behavior.

This is incompatible with Sys-V where stdout/stderr are closed when a process daemonises.

You can do that kind of thing with systemd, but that's linux-specific.

> As a maintainer of the package you probably create some script/unit to start/stop Navidrome, right?

Yep, it's [here](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/audio/navidrome/pkg/navidrome.rc?rev=1.3&content-type=text/x-cvsweb-markup) and the docs for startup scripts is [here](http://man.openbsd.org/rc.subr).

We have a hack to capture the logs and route them to syslog (using `daemon_logger` in the startup script, which uses the [`logger`](http://man.openbsd.org/logger) program), but last time I tried it navidrome still gets killed when `rc` revokes the tty (sending it `SIGHUP`). I will try that again to be sure. I think navidrome would need to call [setsid](http://man.openbsd.org/setsid) to avoid getting a HUP.

Let me check I got this right and get back to you.

I'm quite keen to find a fix because I like navidrome a lot as a music player. It's one of the few bits of software with the "random album" feature!

**Comment by deluan** [comment]
> I think navidrome would need to call [setsid](http://man.openbsd.org/setsid) to avoid getting a HUP

I can easily ignore the SIGHUB signal, if that's what is needed. I can even make it ignore this signal only on OpenBSD.

Let me know.

**Comment by vext01** [comment]
Bear with us, we are seeing if we can get OpenBSD rc to host things that aren't daemons.

Failing that, ignoring SIGHUP may work.

**Comment by vext01** [comment]
We've worked around this in OpenBSD by running any service which doesn't background in a new process group:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/etc/rc.d/rc.subr.diff?r1=1.160&r2=1.161

I'll leave this open in case you are thinking about making navidrome daemonise. Feel free to close this otherwise.

Thanks for the input :+1:

**Comment by deluan** [comment]
Great! Glad you got it working. I don't have any plans to change this behaviour in Navidrome atm, so I'll close this. Feel free to suggest any other improvements you think might be worthy to implement, as long as it does not conflict with other platforms :)
