### ISSUE TITLE
[Bug]: Case sensitive Artist Sort in web client

### ISSUE THREAD

**Issue by SenorSmartyPants** [navidrome/navidrome#3063]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5-SNAPSHOT (8c3919d6)

### Current Behavior

An artist with a lower case name shows up after all the upper case artist names. I noticed this when looking for `a-ha`

![image](https://github.com/navidrome/navidrome/assets/991618/30eb5c4e-e3c0-44bf-b705-8053e21b56de)

### Expected Behavior

I would prefer an option to sort case insensitive. 

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by rkowalsk** [comment]
It probably sorts by ASCII value instead of alphabetically, I'd prefer it to sort alphabetically too.
Feishin's alphabetical sorting uses Navidrome's so this behaviour isn't only for the webui.

**Comment by deluan** [comment]
This was already reported in #2425 and fixed in #2993:

![Screenshot 2024-06-08 at 10 30 32 AM](https://github.com/navidrome/navidrome/assets/331353/466f909a-68c4-40a7-a9da-71d08ccb0c41)
![Screenshot 2024-06-08 at 10 30 17 AM](https://github.com/navidrome/navidrome/assets/331353/63e04540-25d0-4bbc-a734-14d31084818e)


Not sure what's going on with your setup. What is the value of `PreferSortTags` in your config?
Can you try doing a full scan?

**Comment by SenorSmartyPants** [comment]
I do not have `PreferSortTags` set.

Doing a full rescan fix it.

Thanks.
