### ISSUE TITLE
[Bug]: Tracks with ORIGYEAR or ORIGDATE extended tags are sorted into separate albums

### ISSUE THREAD

**Issue by hexateron6** [navidrome/navidrome#3193]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

Looking at my library, I notice one of my albums seems to be split in two:
![image](https://github.com/user-attachments/assets/aa80b359-7d8f-4091-8f64-0fb67cbb9b29)

I notice that one of the duplicate albums contains only one song, and the other contains the rest:
![image](https://github.com/user-attachments/assets/d8e741bd-793e-49b4-a007-74cbad946e6d)

On further investigation, I discover that Still Grey has a different set of extended tags from the rest (being from a different music store). By trial and error, I discover that deleting the ORIGYEAR tag from Still Grey causes it to sort with the rest of the songs. I have had the same issue with songs with ORIGINALYEAR and ORIGDATE/ORIGINALDATE tags too.

I can't imagine why this would be intended behaviour. Some tracks, like songs purchased from Beatport for example, come with several extended tags including ORIGYEAR tags, and if you're like me and like to sort your library into neat categories and complete albums with 'remastered' songs from different sources, this issue makes our job a little harder.

### Expected Behavior

Tracks should be sorted into albums based on only Album, Album artist and Compilation tags

### Steps To Reproduce

1. Use a software like mp3tag to add an ORIGYEAR/ORIGINALYEAR or ORIGDATE/ORIGINALDATE extended tag to one track out of an album.
2. Replace the song on the server with the new tagged song and do a quick scan.

### Environment

```markdown
- OS: Raspbian 11 (bullseye)
- Browser: Firefox 129.0.1 on Windows 10
- Client: Web client
```

### How Navidrome is installed?

Binary (from downloads page)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
This is intentional, the idea behind it is that the Release date (Original Year, and/or ReleaseDate Tags) are often the only way to distinguish between Albums that are
- named the same, but different albums (one artists has two same-named albums)
- different versions of the same album (original version and a remaster version)

You can somewhat control this behaviour with the configuration option `Scanner.GroupAlbumReleases`
https://www.navidrome.org/docs/usage/configuration-options/#:~:text=Scanner.GroupAlbumReleases
You would want to set this to False.

The new Scanner that Deluan is working on #2709 will allow you to finetune this in more details. F.e. only allow albums to be "split" by Album, Albumartist and Musicbrainz_release_id

**Comment by hexateron6** [comment]
I see, thanks for clearing it up!

**Comment by mamema** [comment]
using latest docker image and env var
ND_SCANNER_GROUPALBUMRELEASES = false or ND_SCANNER_GROUPALBUMRELEASES = true

doesn't lead to the expected result to get ONE display album icon (grouping).
Only solution is deletion of the ORGINALYEAR and ORIGINALDATE tags
