### ISSUE TITLE
[Bug]: Edge android brower can't play a very long (20 minutes) audio file.

### ISSUE THREAD

**Issue by ghost** [navidrome/navidrome#3197]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5 (c5560888)

### Current Behavior

Edge android brower can't play a very long (20 minutes) audio file.

I tested other browsers on my phone, and they all worked well.

### Expected Behavior

Normal playback.

### Environment

```markdown
- OS:android 10
- Browser:edge Edge 127.0.2651.90
- Client:web
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/root/navidrome/data:/data"
      - "/root/navidrome/music:/music:ro"
```

### Relevant log output

```shell
time="2024-08-19T00:57:26Z" level=info msg="Streaming file" artist="未知" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 requestId=cb635aca78b3/ylUo7FbC8W-003369 title=test transcoding=false user=wnenw
time="2024-08-19T00:57:26Z" level=info msg="Streaming file" artist="未知" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 requestId=cb635aca78b3/ylUo7FbC8W-003370 title=test transcoding=false user=wnenw
time="2024-08-19T00:57:27Z" level=info msg="Streaming file" artist="未知" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 requestId=cb635aca78b3/ylUo7FbC8W-003371 title=test transcoding=false user=wnenw
time="2024-08-19T00:57:41Z" level=info msg="Streaming file" artist="未知" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 requestId=cb635aca78b3/ylUo7FbC8W-003372 title=test transcoding=false user=wnenw
time="2024-08-19T00:57:42Z" level=info msg="Streaming file" artist="未知" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 requestId=cb635aca78b3/ylUo7FbC8W-003373 title=test transcoding=false user=wnenw
time="2024-08-19T00:57:43Z" level=info msg="Streaming file" artist="未知" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 requestId=cb635aca78b3/ylUo7FbC8W-003374 title=test transcoding=false user=wnenw
```

### Anything else?

[music-new](https://1drv.ms/u/s!AjUhMEyrls9_gbkXZ_SAy9YeHQzbZQ?e=UwzzKm)

![25be6c331924c1a9e2e053a2f3326c0](https://github.com/user-attachments/assets/00359323-6a52-4df7-8f79-1d90608a1a8a)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by kgarner7** [comment]
The file you have appears to be corrupted. Neither ffmpeg nor taglib are able to fully read it.
Taglib
> TagLib: MPEG::Properties::read() -- Could not find an MPEG frame in the stream.

FFMPEG (`ffmpeg -i test.mp3 test2.mp3`)
> [aac @ 0x5582aee30340] Input buffer exhausted before END element found 
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input
[aac @ 0x5582aee30340] channel element 2.4 is not allocated
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input
[aac @ 0x5582aee30340] channel element 2.0 is not allocated
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input
[aac @ 0x5582aee30340] Number of bands (39) exceeds limit (21).
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input
[aac @ 0x5582aee30340] channel element 3.9 is not allocated
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input
[aac @ 0x5582aee30340] channel element 2.9 is not allocated
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input
[aac @ 0x5582aee30340] Reserved bit set.
[aac @ 0x5582aee30340] Prediction is not allowed in AAC-LC.
[aist#0:0/aac @ 0x5582aee06a40] [dec:aac @ 0x5582aee06280] Error submitting packet to decoder: Invalid data found when processing input

The fact that some clients are playing is because they are likely ignoring these errors. You need to fix the file you have.

**Comment by kgarner7** [comment]
No idea. However you got the file is corrupted, and the common tools I use are only able to get a little over 6 minutes of audio from the file before giving up. I would recommend just trying to find the source again, and make sure it actually works. Alternatively, if you're fine with just those six minutes, `ffmpeg -i test.mp3 -q:a 0 out.mp3` can extract that portion

**Comment by kgarner7** [comment]
Same thing; I get 6:15 out of the track via ffmpeg before it gives up.
