### ISSUE TITLE
UX feature request: Add link to artist from song view

### ISSUE THREAD

**Issue by ackl** [navidrome/navidrome#472]
It's not possible to click straight through to the artist of a song from the song list view, even though it's possible to click on the album each song belongs to.

**Comment by deluan** [comment]
This is a current limitation because not all artists are in the DB, only artists that have albums. Only Album Artists are stored in the Artist table. 

Currently it is not easy to know if a particular artist_id is in the DB or not (from the results of the rest API), so I rather not create the link ATM. If I blindly add the link, it would work for the artists you do have albums, but would break the UI for artists that do not have albums....

Once #211 is done, this will be possible.

**Comment by certuna** [comment]
Yes, #211 will enable a lots of worthwhile UI features/filters/etc going forward.
