### ISSUE TITLE
Metadata for database

### ISSUE THREAD

**Issue by pablito7** [navidrome/navidrome#497]
Hello! I'm currently using a music folder where my music files sometimes don't have a correct metadata and I can't change it for several reasons. I was wondering if is there any mean to have a metadata database, like it happens with foobar2000 plugin External Tags. The tags are stored in SQLite database or written as external files to the same directory as the target audio files.

This also could help other users that prefer specific folder structure types.

**Comment by deluan** [comment]
To make the scanner read the metadata from an external file is doable. I will leave this open but I won't be able to work on this any time soon.

**Comment by jrwren** [comment]
I could try to implement this feature.

@pablito7 do you have an example of filename and the format of the metadata? Or are you looking to used the .tag files that foobar2000's External Tags does? 

A binary dump APE tag? http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/External_Tags_(foo_external_tags)

**Comment by deluan** [comment]
Hey @jrwren, thanks for volunteering! Other ideas related to this are:
- Infer metadata from the path (#560)
- Instead of scanning, just importing a `beets` DB (and keeping in sync)

We should try to implement this in a way that makes these other options easier. For this issue and #560, I think the best way would be to implement a new `metadata.Extractor`, for the second (`beets` import) we would have to use a different `scanner.FolderScanner` implementation.

For this specific issue I'd take a look at the [CUE sheet](https://en.wikipedia.org/wiki/Cue_sheet_(computing)) format. That way we could also support single FLAC with CUE albums.

@pablito7 , can you attach in this story an example of this "external file" generated/used by the External tags foobar2000 plugin?

**Comment by jrwren** [comment]
All that is a bit much for me to take on.

**Comment by deluan** [comment]
I know, I'm just saying that we should implement this thinking about the "great picture". For the issue at hand, you'll probably just need to implement a new `metadata.Extractor`, reading an external file. I suggested using the CUE sheet format, but I'm open to any format that is standard and is wide accepted/used

**Comment by certuna** [comment]
I think adding all this external metadata is a slippery slope, there's no end to things that people want to tack on externally, we'll end up with a scanner like Plex that tries to infer and pull tons of info from everywhere.

**Comment by cascooscuro** [comment]
> 
> 
> I know, I'm just saying that we should implement this thinking about the "big picture". For the issue at hand, you'll probably just need to implement a new `metadata.Extractor`, reading an external file. I suggested using the CUE sheet format, but I'm open to any format that is standard and is wide accepted/used

I would love to see this implemented. 
Foobar uses external .tag files, which are binary dumped APE tags (http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/External_Tags_(foo_external_tags))
I have attached two examples of APE tags, one "file" tag and one "folder". Looks like in foobar you can use per-file or per-folder tags:
[external_ape_tags.zip](https://github.com/deluan/navidrome/files/5486889/external_ape_tags.zip)

Of all the available formats I'm not sure which one is better

**Comment by J4gQBqqR** [comment]
I would also add a comment on supporting cue sheet format. 

Currently, cue support only exist in MPD. Airsonic advanced has a pull request on it. Funkwhale and Ampache refuse to support it (won't fix tagged). The reason is simple, just like what @jrwren mentioned, too much work.

For many wav and flac albums under cue, there is currently no good server/client solution for it. MPD is designed to accomplish another kind of task.

**Comment by J4gQBqqR** [comment]
> I would also add a comment on supporting cue sheet format.
> 
> Currently, cue support only exist in MPD. Airsonic advanced has a pull request on it. Funkwhale and Ampache refuse to support it (won't fix tagged). The reason is simple, just like what @jrwren mentioned, too much work.
> 
> For many wav and flac albums under cue, there is currently no good server/client solution for it. MPD is designed to accomplish another kind of task.

Update:
Airsonic's "CUE support" pull request author does not want to support code review. The chance that this will be merged into airsonic is slim. Beets music organizer has an issue opened on CUE for years. Not seeing any development effort on it.

The reality is, this kind of "higher hanging fruits" will never see developments until all the lower hanging fruits are accomplished. That is why ONLY mature platform such as MPD has this kind of feature.

**Comment by certuna** [comment]
Cue sheets are also a bit of a holdover from the 1990s (it's a format for authoring CD masters), I'm not sure if there's a big audience for it going forward. Probably we're better off supporting chapter markers in mp4/id3? Those are still used a lot in podcasts.

**Comment by bartkummel** [comment]
Regarding CUE sheets: I would be very interested to have this feature. I have quite some WAV and FLAC files. IMO the best solution for gapless playback, especially for live recordings. 

Let me know if I can be of any help. I can probably not help programming it, since I’m not into Go. But e.g. testing I’d be happy to help with.

**Comment by bartkummel** [comment]
There's now also a [separate issue](#2136) requesting support for `.cue` files.

**Comment by dweymouth** [comment]
> IMO the best solution for gapless playback

I'd say that using a client that supports gapless is the best solution :)

I'd think proper support of Navidrome for cue sheets should split the tracks on-the-fly so that clients can seek to specific tracks (which on the server side are actually just time indexes into a specific Wav/Flac), add individual tracks to playlists, etc. In which case, gapless would still be broken if the client doesn't support it

**Comment by bartkummel** [comment]
Yes, that's right. The good thing about single files with a CUE file on the side is that you can always fall back to playing the single file. That'll playback gapless on every client, at the price of not being able to skip tracks of course. I like the idea of splitting on the fly, as long as I can keep my single files on the server.

**Comment by dweymouth** [comment]
> you can always fall back to playing the single file. 

How would this work for Subsonic clients? For Navidrome's web client it could expose a new property where the web frontend could request the file to be pre-split into tracks or not depending on playback context, but for Subsonic there is no concepts of different versions of the same media

**Comment by deluan** [comment]
Whenever this is implemented, it will be exactly like @dweymouth described: The server will slice the single file on demand (and probably cache the results). The client won't be able to know the difference, so it won't be able to "fall back to the single file", unless the single file is not indexed by a .cue, which you could do by duplicating the file (not a great option, though).

Please let's continue the discussion about .CUE support in its own issue, #2136
