### ISSUE TITLE
Can the UID and GID set through Docker environments options?

### ISSUE THREAD

**Issue by BobWs** [navidrome/navidrome#531]
Hi,
Can I set the Users UID en GID via the Docker environments options? Will this work?

**Comment by deluan** [comment]
No it won't... I would have to add some logic to the container image to enable this. That's how the LinuxServer.io images work. 

Question: What is your use case for this? Can't you just call docker with `--user ${UID}:{GID}`? If using docker-compose, you can set it in the `docker-compose.yml` file with ex: `user: 1000:1000`.

**Comment by BobWs** [comment]
Well I’m using Docker on a Synology NAS and they have a nice GUI to configure the Docker containers. So the easiest and logical way to add GID and GUI in this case is via the GUI environment tab. Indeed the same way as linuxserver.io is doing it. 

e.g. like this

![image](https://user-images.githubusercontent.com/5485820/94371487-36213480-00f7-11eb-8f88-49effcfc2c67.jpeg)

But as you stated that it isn’t possible for now so I guess I will have to do it by CLi.

**Comment by deluan** [comment]
We discussed the possibility to enable this functionality (setting UID/GID with env vars) [in the past](https://discordapp.com/channels/671335427726114836/671335427726114839/695633350781698078), but decided agains it because:
1) This is a responsibility of Docker itself (or the container platform used), not the app
2) I plan to eventually rewrite the docker images to be based on LinuxServer, and this is a given in their images.

I'll keep this open, and will use this to track the LinuxServer "migration".  

It would be awesome if someone could step-up and contribute with this....
