### ISSUE TITLE
Allow changing server name

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#532]
In the `navidrome.toml` file, it'd be nice to be able to set the values `ServerName` and `ServerShortName` for the server. This would then:
- set `name` and `short_name` attributes in the `/app/manifest.json` file
- put `ServerShortName` in the `react-admin-title` element in the top bar (which currently says things like `Navidrome - Albums - All`, this would become `MyServer - Albums - All`)
- show `ServerName` on the user login screen ("Welcome to MyServer" or something similar)

Default values for both would be `Navidrome`

(reason for this request is that you will currently get a new, identical looking "Navidrome" app for each server you install/pin-to-homescreen as PWA).

**Comment by deluan** [comment]
This is a good idea, but for this item:
> show ServerName on the user login screen ("Welcome to MyServer" or something similar)

you can accomplish something similar to that effect by using the `UIWelcomeMessage`. So if it is set to _"Welcome to MyServer"_, this is what you get in the login page:
<img width="353" alt="Screen Shot 2020-09-27 at 10 48 04 AM" src="https://user-images.githubusercontent.com/331353/94367848-12d29700-00af-11eb-89f5-a7ba0ea9e4cb.png">

I think this is better, but I'm open to different opinions

**Comment by selfroasted** [comment]
Hey, big fan of Navidrome. I'm about 2 weeks into hosting it, and I love it! I chose it over all the *sonic variations because its just easy and great! I do agree with this post that a little more customization options would be nice. I have added the custom text via UIWelcomeMessage but having some additional options like title text as u/certuna suggested would be very helpful, especially because I plan to get a couple of these servers going. I don't want you to think I'm trying to strip the Navidrome branding, but rather differentiate my eventual multiple Navidrome servers. Thanks again for the awesome project, and for being so responsive to users!

**Comment by certuna** [comment]
If anyone wanted to strip the Navidrome branding it would be trivial anyway, just change some icons & values in the HTML and compile ND yourself.

**Comment by certuna** [comment]
Alternatively, you could add the option to load an external manifest file, which would replace the default one. Something like this in the `navidrome.toml` file:
`Manifest = "/Users/dieterbohlen/navidrome/manifest.json"`

**Comment by deluan** [comment]
Re: overriding the `manifest.json` file, but what about the base_url? Users who want to change it would have to change in two places? :(

**Comment by certuna** [comment]
`start_url` in the manifest and `base_url` in the settings, do they do the same things?

**Comment by deluan** [comment]
BaseURL is the path context in the URL. Ex: If you want Navidrome in www.mydomain.com/music, BaseURL has to be set to `/music`.

I think `start_url` has to be set to `${BaseUrl}/app` (this is the path for the UI)
