### ISSUE TITLE
Adding a song to the queue with "Play Next" while paused breaks the player

### ISSUE THREAD

**Issue by srichter** [navidrome/navidrome#650]
## Expected Behavior
The track is added to the queue after the currently playing (but paused) track. The player functions properly and is able to be unpaused.

## Current Behavior
The track is added to the queue after the currently playing (but paused) track. The player's play/pause button changes to display pause icon, suggesting the player thinks it is in the playing state. The player is unable to be unpaused and the play/pause button doesn't work. The track either has to be skipped or paused/unpaused from the queue list to resume play.

Sometimes, when "Play Next" is selected while the player is paused it will immediately start playing from the beginning of the queue. I have not been able to reliably reproduce this behavior yet, but I believe it happens after the "fix" described above of pause/unpausing the track directly from the queue list.

## Steps to Reproduce
1. Have a queue of tracks with a track playing
2. Pause the player
3. Select "Play Next" on a track
4. Attempt to unpause the player

## Context (Environment)
macoS, Navidrome 0.38.0, Chrome 87.0.4280.67 (also reproducible in Firefox)

**Comment by srichter** [comment]
> Sometimes, when "Play Next" is selected while the player is paused it will immediately start playing from the beginning of the queue. I have not been able to reliably reproduce this behavior yet, but I believe it happens after the "fix" described above of pause/unpausing the track directly from the queue list.

Okay I've been able to reproduce this:

1. Have a queue playing and be on any track except track 1
2. Select "Play Next" on a track
3. Select "Play Next" on another track
4. The queue restarts from track 1

**Comment by HassanRahim26** [comment]
Hey @srichter ,
I am interested in working on this issue. However, I am not very familiar with the codebase. Can you please guide me about how to proceed with solving this?

**Comment by YashJipkate** [comment]
Hey @srichter @deluan, one of the solutions for this (where it starts playing from the beginning) is to remove the `playIndex: undefined` in [playQueue.js#122](https://github.com/navidrome/navidrome/blob/cdfdf78c734d8d9a3b6fb209656eb79bd9d51ec2/ui/src/reducers/playQueue.js#L122) and have the `playIndex` computed in the [PLAYER_PLAY_NEXT case](https://github.com/navidrome/navidrome/blob/cdfdf78c734d8d9a3b6fb209656eb79bd9d51ec2/ui/src/reducers/playQueue.js#L85). This works because the `playIndex: undefined` was overriding the computed `playIndex` in the `PLAYER_PLAY_NEXT` case. 

One thing is that it will start playing the correct song, irrespective of whether it was paused or had played for some time. I think that might occur because we refresh the audio list by passing `clear: true` in the [PLAYER_PLAY_NEXT case](https://github.com/navidrome/navidrome/blob/cdfdf78c734d8d9a3b6fb209656eb79bd9d51ec2/ui/src/reducers/playQueue.js#L85)? I am thinking this is not a regression but expected by the Jinke-player?

This is how it looks if I do the above changes - 

https://user-images.githubusercontent.com/34203227/113571032-2f89f180-9633-11eb-8824-3e3f6e50054d.mp4

Should we go forward with this? Thoughts?

**Comment by srichter** [comment]
In your video the player resets the song that was playing to the beginning when you select "Play Next"; I don't think that's desired behavior either.

**Comment by YashJipkate** [comment]
@srichter yes, that's the problem :( 
I did some digging into this and found that the 'pause' state changes somewhere just after the updating of the queue. I logged every case in the playQueue reducer to see where the queue state is being changed but found that it remains on pause till the syncing of the queue but somehow the onAudioPlay handler is invoked just after, and the track starts playing from start. No action for the queue state is performed in between.

I am guessing this might be something with the Jinke player? Or maybe some prop might be missing (still unlikely, I mean changes to the queue state still have to go through the reducer, right?)

What do you think @srichter @deluan?

**Comment by srichter** [comment]
From my past research into this I believe I narrowed it down to either the play next reducer clearing the queue or playindex when it returned the state, but didn't get a fix implemented. I had been playing around with the queue to try to implement saving the queue position in localStorage to be able to restore it in a future session. I wonder if it may make sense to rebuild the queue in a different way that can better handle these and other features. I'll let Deluan provide some input and see what his thoughts are.

**Comment by YashJipkate** [comment]
> either the play next reducer clearing the queue or playindex when it returned the state

The playlist refreshes in the play next reducer because we have the `playIndex: undefined` return from it, which overrides the playIndex of the `previousState`. I got around this by passing the playIndex in the state. Now although this preserves the song that was being played (it doesn't go to the first one), it however it starts playing from the beginning (as shown in the screen recording I posted above).

According to the logs, the queue with all its data (current and playIndex) is well maintained till the sync queue reducer, after which the audio play event is fired, which starts the song from the beginning.

One observation is that this behaviour does not occur when you update the queue via Play Later. My guess is that when we fiddle with the ordering of the list, it upsets the Jinke player?


> I wonder if it may make sense to rebuild the queue in a different way that can better handle these and other features.

That can also be a good workaround, it'll hopefully prevent the loss of state.

**Comment by deluan** [comment]
Jinke player queue management is kind of messy.... It mixes declarative (using `audioLists`) with imperative syntax. Some features were added to it after Navidrome was already using it, and I think the best option would be a complete rewrite of the queue management actions/reducers. 

As we are approaching the implementation of the Jukebox (#364) functionality, where we will need to control the server-side player with the same web-UI as the audio instance in the browser, we may need to rethink our dependency on Jinke player, replacing it or actually contributing to its code base to make it more flexible.

**Comment by RitikPandey1** [comment]
Hey @deluan, In my opinion, currently there is no need for a complete rewrite of the queue management. The queue starts first song when adding the next song is because the prop `clearPriorAudioLists` is set to be true when the next song action gets dispatch. `clearPriorAudioLists = true` set `playIndex` to 0, But if we set `clearPriorAudioLists=false` then new song not get added to correct place. I've gone through the react-music-player code and found the bug, that it adds all new songs at the end of the queue while updating the audio list, and that's why `playLater` works correctly. 
I've opened the [issue](https://github.com/lijinke666/react-music-player/issues/343) on the react-music-player repo. 

PS: I may be wrong, so please correct me if I miss something

**Comment by YashJipkate** [comment]
@RitikPandey1 I don't think that's a bug. That's the expected behaviour when you set clear audio lists to false. For the queue to have a different ordering, the previous list needs to be cleared, or it'll just add to the existing list/queue.

Looking at the issue you opened, I have a strong feeling that you'll get the same answer there :P

**Comment by RitikPandey1** [comment]
@YashJipkate I'm talking about updating the current `audioList`, if `clearPriorAudioList=false`  then the  `updateAudioList` function of react-music-player only add new songs at the end, updating audio list doesn't mean add all song at the end. If you want to see the implementation of the `updateAudioList` function you can check the latest comments on issue I've opened on react-music-player.

**Comment by YashJipkate** [comment]
@RitikPandey1 according to [this comment](https://github.com/lijinke666/react-music-player/issues/343#issuecomment-814602347) on the thread, he says that `clearPriorAudioList=false` shouldn't be used. I already tried the solution that he proposed about adding `playIndex`, the thing is that, as I've mentioned above it starts the 'correct' (i.e. not beginning of the queue) song from the beginning. 

I think that [this line here](https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2109) is the main cause for the loss of play state.

**Comment by RitikPandey1** [comment]
> I think that [this line here](https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2109) is the main cause for the loss of play state.

Yeah you're right.

**Comment by deluan** [comment]
> @RitikPandey1 according to [this comment](https://github.com/lijinke666/react-music-player/issues/343#issuecomment-814602347) on the thread, he says that `clearPriorAudioList=false` shouldn't be used. I already tried the solution that he proposed about adding `playIndex`, the thing is that, as I've mentioned above it starts the 'correct' (i.e. not beginning of the queue) song from the beginning - whether it was paused and/or progressed, effectively losing its play state.
> 
> I think that [this line here](https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2109) is the main cause for the loss of play state.

I haven't spent too much time analyzing this issue, so my question to you guys is: Did we find the issue? Is it feasible for us to create a PR in the React-Jinke-Player repo to fix this?

**Comment by YashJipkate** [comment]
I'll raise an issue (with a fix if I could find it) in the Jinke repo, to see what the creator has to say on this. I'll update this thread if I get anything.

**Comment by deluan** [comment]
This was fixed in 0.49.0. This issue is still open because I lost it in the ocean of open issues :)

https://user-images.githubusercontent.com/331353/223894076-cc9f4da5-cf39-4380-b167-008c695ed015.mov

If you are still getting it, it may be in a different situation, can you please try to isolate the issue, with clear steps on how to reproduce it? Thanks.

**Comment by swaqvalley** [comment]
Okay, I tried again today and adding one track via Play Next works the same as in your attached video. But if I add two tracks back-to-back the playing restarts from the first track in the playlist.

**Comment by deluan** [comment]
Yeah, you are right. Thanks for reporting back. I'll try to solve this, but it may not be feasible with `react-jinke-player`.
