### ISSUE TITLE
Possibility to integrate Navidrome into Google Home/Assistant?

### ISSUE THREAD

**Issue by garret** [navidrome/navidrome#682]
I want to ditch YouTube Music/Spotify as music services for Google Assistant. In particular, I have a set of Google Nest Minis which I command by voice asking to play some music from my library on Youtube Music. 
One could upload all its library to YouTube Music but I can see that now for playlist reproduction you need a (paid) pro account. That annoys me as it could be easily mane gable with Navidrome. 

Thus, do you know if it would be possible to integrate somehow Navidrome as music service for google home?

**Comment by certuna** [comment]
There is something similar for Plex, although it only does video, not music: https://github.com/maykar/plex_assistant/issues/50 , so if someone wants to create a Navidrome Assistant for Google, that's probably the way to do it.

Also, "[jukebox mode](https://github.com/deluan/navidrome/issues/364)" would also need to be implemented in Navidrome first, where an application can instruct the server where to stream to (i.e., to the Google speakers).

**Comment by SteveDinn** [comment]
As I currently understand it, it's not easy (maybe not possible?) to create an app that works with the Google Assistant without making it public. And it doesn't make sense to have a public service that does things with your personal, self-hosted Navidrome instance. This would probably have to be something that lives in the cloud and to which you delegate some amount of control.

I tried to go down this road with another open-source product (Home Assistant) and quickly found out why the "parent" company (Nabu Casa) offers subscriptions and a single, centralized Google assistant integration.

Believe me, I'm all for this idea, but I just don't know how feasible it is.

**Comment by certuna** [comment]
In this [Plex Assistant](https://github.com/maykar/plex_assistant) thing you seem to be able to set your own direct server URL, so somehow this does work with localized server settings.

**Comment by SteveDinn** [comment]
Yes, but the control itself is coming from a central instance of the assistant app. Local control is possible, but not without that over-arching central web service app in the cloud. It can probably be a very simple app, that just maps your "home" to your instance of Navidrome, and redirects to your local instance. But that means that the information about your local instance needs to be stored somewhere. Once you have to start storing user data, you need to be concerned with securing it, and it suddenly all becomes more complicated :)

But the real problem with open source apps integrating with the assistant is that they have to have this web service hosted somewhere. This costs money, and open source development generally has none to spend, which is why there exists a subscription model for most of these things.

**Comment by garret** [comment]
Ok, it seems that the easy answer is just 'no'.

**Comment by deluan** [comment]
This is something I'm also interested in implementing. Didn't spend too much time researching it, but I'm pretty @SteveDinn is right in that it will need an external web service, and not just your own instance of Navidrome. I'll keep this open until I decide what to do (or someone comes up with a solution)

**Comment by garret** [comment]
If one has home assistant and google or alexa speakers, maybe there is a way to cast the stream somehow?

**Comment by Manas502** [comment]
Didn't get you @garret

**Comment by garret** [comment]
> Didn't get you @garret

Sorry, just wrote very fast before :/ 

I was thinking today if there could be a way to stream music from navidrome on the google speakers if somebody has an home assistant instance already connected to google assistant. Home assistant allows to stream content to the google speakers. A routine in google assistant can trigger an automation in home assistant. That automation could be to stream the music from navidrome to the google speakers.

**Comment by SteveDinn** [comment]
If you're suggesting that somebody write a subsonic server integration for home assistant, them I'm all for it, and I think that would be awesome, but you're in the wrong project :)

**Comment by bjhiltbrand** [comment]
It's been a while since I have messed with this (like 2 or 3 years), but here is a simple API that someone wrote to interface with dialog flow in Google Assistant. I took it and made some changes to fit my needs as far as commands go. It was far from perfect, but it was working. I will have to look at dusting it off again. Maybe some of the principles could be implemented within Navidrome so you don't have to spin up a separate translation layer as a different service.

https://github.com/ctrlaltca/google-home-subsonic

**Comment by EdgarVerona** [comment]
As a home assistant user, I can confirm that your suspicions are correct @bjhiltbrand - I have a local Google Assistant integration going with Home Assistant, and it keeps the communication entirely between my server and Google at the expense of a bit of one time manual setup.

**Comment by codeinabox** [comment]
There is a [discussion about adding Subsonic support to the Music Assistant integration for Home Assistant](https://github.com/orgs/music-assistant/discussions/414)
