### ISSUE TITLE
Gapless playback

### ISSUE THREAD

**Issue by ben-connors** [navidrome/navidrome#745]
Currently, network and transcoding delays add a short gap between tracks, which is rather distracting for tracks that are supposed to be played without pause (e.g. sustained notes crossing track boundaries). Would it be possible to add gapless playback support to the web player?

**Comment by deluan** [comment]
The web player comes from another project, [react-jinke-music-player](https://github.com/lijinke666/react-music-player), so Gapless playback needs to be implemented first there.

I opened an issue with that project a while ago, but the dev hasn't prioritized it. PRs are welcome: https://github.com/lijinke666/react-music-player/issues/81

I'll keep this issue opened (and flagged as blocked), so others can easily find it and may even contribute to it.

**Comment by ScrumpyJack** [comment]
Gaps make listening to classical music and particularly opera, painful. I'd love gapless playback

**Comment by bbsixzz** [comment]
Your issue with the project was closed on 6 Feb 2020 and the dev seems totally uninterested.

Gapless playback is kind of a big deal for most users, shouldn't we look for a replacement?

**Comment by wgroeneveld** [comment]
I've noticed the same small but very irritating gaps between tracks. Is this something that's currently being looked into? I didn't even know the client player is based on another project, it's not referenced in the main readme file in this repo?

**Comment by hauke725** [comment]
lijinke666/react-music-player seems abandoned now, maybe as @bbsixzz said it's time to look for a replacement

**Comment by magrubertone** [comment]
Just chiming in to say I was excited to start using Navidrome but gapless playback is essential so I'll be avoiding it for now.

**Comment by dweymouth** [comment]
This is an old issue but @magrubertone I thought I'd chime in (for you or anyone else to say that if you want gapless playback, your best bet is to use a Subsonic client. There are several Subsonic clients that support gapless playback, including DSub for Android, iSub for iOS, Feishin (successor to the popular Sonixd, in early development) and Supersonic (working name of my client, in early development) for desktop OSes.

Gapless playback with web audio APIs is [impossible](https://lists.w3.org/Archives/Public/www-archive/2014Oct/0007.html), or at least nearly so. (Article is from 2014, but I believe the state of browser audio APIs hasn't moved forward since then.) There are libraries like [Gapless5](https://github.com/regosen/Gapless-5) which fake it quite well, and perhaps Navidrome should use this once a rewrite of the web player is undertaken, but perfect gapless playback likely isn't possible in the browser. Even Spotify's web client doesn't support it.

**Comment by tcurdt** [comment]
It sounds like a lot of work but... shouldn't this be something that is possible with WASM?

**Comment by dweymouth** [comment]
Yeah, you might be right, didn't think about WASM, just the standard HTML/JS APIs. Would be a *lot* of work probably because I don't think there's anything like libffmpeg for WASM ;)
