### ISSUE TITLE
Constant CPU usage since 0.40

### ISSUE THREAD

**Issue by SteveDinn** [navidrome/navidrome#777]
Since upgrading to 0.40, I've experienced constant CPU usage of around 2 - 4% on my RPi 4. This is apart from the periodic scans (which are recognisable spikes) and any transcodes (which are a separate process anyway).

![Screenshot_20210213-104025](https://user-images.githubusercontent.com/3911507/107852705-a69bca00-6de8-11eb-8097-3eecdc802c20.png)
![Screenshot_20210213-103909](https://user-images.githubusercontent.com/3911507/107852707-a996ba80-6de8-11eb-81c9-bac4eb23eaf7.png)

You can see that for 5 days of uptime, the main navidrome process has used more than 8 hours of processor time, when, frankly, I've barely played anything.

**Comment by deluan** [comment]
Hummm, seems that this is being caused by the Diode library I'm using to buffer messages to the Activity Panel. I'm using the [polling method](https://github.com/cloudfoundry/go-diodes#poller), that polls every 10ms for new messages.... I'll experiment with the Waiter implementation or increasing the poll interval to 100ms

Thanks for reporting this

**Comment by SteveDinn** [comment]
If this is literally just for notifications to the activity panel, is even 1 second too long? I mean, I can live with 1 second of latency between something happening and getting notified about it. I don't think it's necessary to check 10 times per second, let alone 100 times per second.
