### ISSUE TITLE
Scanning Stops at 21000 Songs

### ISSUE THREAD

**Issue by TheFlatworm** [navidrome/navidrome#785]
I keep getting an infinite loops of Navidrome scanning music - it scans until 21000 or so and then starts the scanning over - repeating indefinitely.  Running :latest navidrome in a Docker container on a RasperyiPI 4, Debian Stretch with OMV5.

**Comment by deluan** [comment]
Does it restart (do you see the "Navidrome" banner again when it restarts the scan)? 

It may be that the system does not have enough RAM, and it crashes, then starts again. The scan process uses a considerable amount of memory. I've seen that on the demo instance, it had 512MB with no swap area. The solution was to configure a swap area of 1GB.

Let me know if this is your case. If not, send me the last lines in the log before it restarts. How many songs do you have in your library?

**Comment by TheFlatworm** [comment]
Hi - sorry I was away.  Navidrome doesn't restart, the scan justs stops and starts over at 0, and then counts rapidly to 21000 or so and then starts again.  Ram should be fine - it has access to the full 4MB of ram.

The last line in the log before restart is 

`time="2021-02-27T00:34:09Z" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=1m12s folder=/music playlistsImported=0 updated=0`

My music library count is: 

```
Album count | 21381
Artist count | 7199
Song count | 342665
```

**Comment by deluan** [comment]
By default, Navidrome checks for new or changed files every 1 minute. The number you see (~21000) is the number of folders found in your library) 

If all your music is there, then that's the expected behaviour.  If you don't want/need the periodic scan, you can change the interval with the `ScanInterval` [config option](https://www.navidrome.org/docs/usage/configuration-options), or disable it completely (setting it to `0`). If you disable it, you will need to trigger a rescan when you change or add music to your library.

Let me know if this answers your question

**Comment by TheFlatworm** [comment]
Thank you!!  That solves it!
