### ISSUE TITLE
Add docker image for spotify integration

### ISSUE THREAD

**Issue by TaakoMagnusen** [navidrome/navidrome#978]
Would it be possible to release docker images with spotify integration builtin? Maybe alongside the standard docker releases with a `-spotify` appended to the image tag?

As a complete aside: the docker hub tags are kind of a mess with so many tags being named after SHA hashes...

**Comment by deluan** [comment]
If you are referring to [integrating with Spotify](https://www.navidrome.org/docs/usage/external_integrations/#spotify), Navidrome is already "integrated" with Spotify out-of-box, is just need a personal key/secret.

We cannot add a personal key/secret as part of Navidrome because it is, well, personal. If we add a key, it would be shared by all users, so it would be used by so many people that you'd run into rate limits imposed by Spotify's API. Having a personal key resolves this, by not sharing the API quotas with anyone else. 

And when you upgrade Navidrome, you don't need to recreate the keys, it is a one-time only configuration.

Regarding the tags, users should use `latest` or a specific version like `0.41.0`. The `sha-` and `pr-` are development builds and sometimes I point these to users to test and help troubleshooting a specific issue.  But to your point, to avoid confusion, I may push them to a GitHub registry, and keep the Docker registry with only "production" images

**Comment by TaakoMagnusen** [comment]
@deluan thanks! I just saw this page: https://www.navidrome.org/docs/usage/configuration-options/#environment-variables

that lays out all the environmental variables. I'd suggest calling out this page specifically in the DockerHub Overview for Navidrome, i did a quick cntrl+f for "spotify" and "environment" and didnt see anything that lead me to believe the docker image allowed for more environmental variables. But I definitely take some responsibility for not RTFM.

Thanks for the info! Didn't realize integrating spotify was so easy!

Again, thanks for the amazing project and help!
